### ISSUE TITLE
Using beta versions of Preact causes peer dependency error

### ISSUE THREAD

**Issue by abeaclark** [developit/preact-compat#120]
I am running preact-compat in production on AWS which uses Node 2.1.1

Running into the following error: 
```
error peerinvalid The package preact@5.0.1-beta.15 does not satisfy its siblings' peerDependencies requirements!
error peerinvalid Peer preact-compat@1.11.0 wants preact@*
```

The `*` doesn't pick up beta releases.

The only thing [I could find](https://semver.npmjs.com/) to accept all current versions of preact is:
`* || >3.0.0-beta0 ||  >5.0.0-beta0 || >5.0.1-beta.0 || >5.1.0-beta.0`

Any thoughts?

**Comment by developit** [comment]
@abeaclark Yeah, this has been a pain for a bit.  I'm going to roll Preact 5 over as the main stable version tonight so this will go away.  That semver hack will be useful next time there is a beta though...

**Comment by abeaclark** [comment]
@developit Ok great. Thanks for all the hard work!

**Comment by developit** [comment]
Preat 5.3.1 is now stable!
