### ISSUE TITLE
PropTypes validation isn't occurring against Stateless Function Components

### ISSUE THREAD

**Issue by ctrlplusb** [developit/preact-compat#124]
I was attempting a PR to soften the proptypes errors into warnings as we discussed on twitter but noticed this issue.  I will look into it, but thought it worth logging in the interim.

**Comment by ctrlplusb** [comment]
This is a tricky one, because we only figure out if it's a stateless functional component during the render cycles within `preact`...

**Comment by developit** [comment]
That's probably the best way, yeah. Could actually hook creatElement, detect when `vnode.nodeName` is a pure functional component, and inject a wrapper around it that does the validation.

**Comment by ctrlplusb** [comment]
HOC it. :)

**Comment by developit** [comment]
Yup, basically. I think that will keep things happening at the expected time when rendering.
