### ISSUE TITLE
PropTypes validation doesn't take default props into consideration when rendered on server.

### ISSUE THREAD

**Issue by ctrlplusb** [developit/preact-compat#126]
I'll try look at this one too.

**Comment by ctrlplusb** [comment]
I'm thinking the issue here may actually lie in the `preact-render-to-string` module.  It's like the default props aren't being applied.  As stated, it's only in server rendering, client side all ok.

**Comment by developit** [comment]
Confirmed, it's actually just not applying them. Good catch!

**Comment by developit** [comment]
Closing this out since it's been moved to https://github.com/developit/preact-render-to-string/issues/5
