### ISSUE TITLE
Support for PureComponent

### ISSUE THREAD

**Issue by adriantoine** [developit/preact-compat#139]
Hi,

In [v15.3.0](https://github.com/facebook/react/releases/tag/v15.3.0), React has introduced `PureComponent` which is like `Component` with `react-addons-pure-render-mixin` integrated.

I don't think `preact-compat` supports it at the moment, is it planned?

Thanks!

**Comment by developit** [comment]
Yup! Support is definitely planned, we are just working out whether it will be a feature of preact-compat or something built into preact itself:

https://github.com/developit/preact/issues/163

**Comment by adriantoine** [comment]
Awesome!

**Comment by rfreitas** [comment]
Does the documentation state this difference in implementation? I just spent a day debugging an issue which I think it's related to this.

**Comment by developit** [comment]
No, sorry - it does mention the React version somewhere as being 15.1.0, which didn't have `PureComponent`.  That said, your comment prompted me to add support for it, so if you update `preact-compat`, it's there.
