### ISSUE TITLE
render behaves differently from ReactDOM

### ISSUE THREAD

**Issue by piuccio** [developit/preact-compat#145]
https://facebook.github.io/react/docs/top-level-api.html#reactdom.render

> ReactDOM.render() controls the contents of the container node you pass in. Any existing DOM elements inside are replaced when first called. Later calls use React’s DOM diffing algorithm for efficient updates.

That's not what happens with preact-compat

```html
<div id="root">
   Hello
</div>
```

```js
import ReactDOM from 'preact-compat';

ReactDOM.render(<span>Hello</span>, document.getElementById('root'));
```

results in
```html
<div id="root">
   Hello<span>Hello</span>
</div>
```

**Comment by developit** [comment]
Good catch - is this specific to TextNodes?

**Comment by piuccio** [comment]
no it's the same if you have other dom nodes

**Comment by developit** [comment]
Alright, looking into it. Here's a jsfiddle confirming the React version does as you noted:
https://jsfiddle.net/developit/egj8jt0f/

**Comment by MobiusHorizons** [comment]
I have the same issue. This should be a simple as doing the following

```javascript
    var emptyRoot = root.cloneNode(false); // create empty copy of root
    // Possibly do initial rendering into emptyRoot here
    root.parentNode.replaceNode(root,emptyRoot); // replace root with an empty version;
    root = emptyRoot;
```

**Comment by developit** [comment]
@MobiusHorizons I believe that would break SSR takeover. Though invoking `render()` after replacing might work.

I'm thinking it might actually just be fine to do something like:

```js
let root = render()  // preact's render
for (let i=parent.childNodes.length; i--; ) {
  if (parent.childNodes[i]!==root) {
    parent.removeChild(parent.childNodes[i]);
  }
}
```

Maybe?

**Comment by MobiusHorizons** [comment]
so it ended up that i could just put the current content in `prev` and it would replace properly. 
the above pull request contains a test for the scenario in question and the code to fix it.

**Comment by chiragmongia** [comment]
@developit I'm blocked by this. An ETA on fixing up this issue would be really helpful.

**Comment by developit** [comment]
@chiragmongia Apologies!  I'll merge and release this right away.  I've been trying to set up the next release of Preact, but I think it's actually going to be better split things up into many smaller releases and just let the breaking changes be major versions (even if that means multiple major versions in relatively tight succession).  Regardless, this change is easy so here we go!

**Comment by chiragmongia** [comment]
@developit Thanks a ton! :heart_eyes:
