### ISSUE TITLE
this.refs undefined. 

### ISSUE THREAD

**Issue by dmoskovsov** [developit/preact-compat#151]
Hi, I'm currently trying to migrate for preact. My current project is using react-bootstrap library, and the Dropdown component of it fails with this issue: 

```error: Cannot read property 'focusNext' of undefined(…)```

Where parent of focusNext is reference to this.refs.menu which is undefined. 
My code looks like this: 

```
       <Dropdown>
                    <Dropdown.Toggle ref="toggle">
                     some
                    </Dropdown.Toggle>

                    <Dropdown.Menu ref="menu">
                        <MenuItem eventKey="4">Separated link</MenuItem>
                    </Dropdown.Menu>

                </Dropdown>```


Would be very helpful if you guide me on fixing it. 

Thanks!

PS: 
Versions: 
"preact": "5.7.0",
"preact-compat": "2.3.0",

**Comment by developit** [comment]
Hi @dmoskovsov!

In the component you showed above, are you inheriting from `preact-compat`'s `Component`, or `preact`'s?  String refs only work in preact-compat, and only when used with `createElement()` (not preact's `h()`).

There is another issue relating to Bootstrap's Dropdown here:
https://github.com/developit/preact-compat/issues/146

**Comment by dmoskovsov** [comment]
Trying it now, we'll close an issue, thanks!
