### ISSUE TITLE
ProTypes.func is undefined

### ISSUE THREAD

**Issue by carlosvillu** [developit/preact-compat#173]
Hi,

I am using preact-compat w/ webpack alias to replace ReactJS in my project. In dev mode all work fine, but with the minified production ready I have the follow error in the console:

`Uncaught TypeError: Cannot read property 'isRequired' of undefined`

Here there is a screenshot with more context:

![captura de pantalla 2016-09-03 a las 15 27 49](https://cloud.githubusercontent.com/assets/179462/18225096/86a5e3d2-71eb-11e6-9231-367822fd7a5e.png)

Do you have any idea with can be wrong ?!

Btw, I am using the default uglify config for the webpack plugin.

Thx!

**Comment by developit** [comment]
Are you using the `react` babel preset? If not, try adding the remove-proptypes transform.

**Comment by carlosvillu** [comment]
That is my Babel config now:

```
"babel": {
    "presets": [
      "es2015",
      "react",
      "stage-3"
    ],
    "plugins": [
      "transform-runtime",
      "syntax-async-functions",
      "transform-regenerator",
      "transform-object-rest-spread",
      "transform-decorators-legacy"
    ],
    "env": {
      "production": {
        "plugins": [
          "transform-react-remove-prop-types"
        ]
      },
      "development": {
        "presets": [
          "react-hmre"
        ]
      }
    }
  }
```

But doesnt work. I have the same error.

And that is odd isnt?! Cos that check should be removed.

**Comment by developit** [comment]
Hmm. Is it a class component or a pure function?

**Comment by carlosvillu** [comment]
Is this line in the ReactRouter project

https://github.com/reactjs/react-router/blob/a11a10bdd17a15ec7f0e7ab846d631677ac96baa/modules/InternalPropTypes.js#L11

**Comment by developit** [comment]
@carlosvillu any chance you're using Webpack 2?  Wondering if it's a Dead Code Elimination bug.  I've just done a pretty thorough search through preact-compat and proptypes and I can't seem to find anything that would lead to a dev/prod difference in either.

**Comment by fokusferit** [comment]
@developit I'm just looking through help wanted tag and if there is something I can help with as someone new 😄  
So I'm asking myself if this here is still valid ? As react-router moved to v.4.1.1 and PropTypes are now a dedicated dependency.. 
Ping @carlosvillu

**Comment by carlosvillu** [comment]
I think that we can close this issue. Sorry for no answer early

C.

**Comment by developit** [comment]
Np!
