### ISSUE TITLE
Uncaught Error: Children.only() expects only one child.

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat#174]
It's occur when I try to add `precat-compat` and `preact@beta` on https://github.com/lvarayut/relay-fullstack

Maybe this not support yet?

**Comment by developit** [comment]
Is the error coming from one of the dependencies?  `preact-compat`'s `Children.only()` should match React's:
https://github.com/developit/preact-compat/blob/master/src/index.js#L138

Though really, we could make it a warning instead of an error. Not sure if that fixes the issue though.

**Comment by developit** [comment]
This should be fixed in 3.4.2!
