### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat#176]
I'm at and trying `preact 6.0.2`, `preact-compat 3.0.1` with https://github.com/justinjung04/universal-boilerplate and found that when I click `Go to page` and click `Go to home` I will get an error

```
Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```

Maybe a bug?

**Comment by developit** [comment]
Looks like it! I'll check into it.

**Comment by developit** [comment]
@katopz - I think I have a fix for this locally! Will publish as soon as I have vetted it.

**Comment by developit** [comment]
Fix is on its way. I'm going to close this one out since it's a duplicate of developit/preact#297 and the bugfix will be in that repo.
