### ISSUE TITLE
Cannot resolve module 'preact-compat/lib/ReactTransitionGroup' & module ReactFragment

### ISSUE THREAD

**Issue by struckm** [developit/preact-compat#186]
I'm trying to convert an existing React application based on Material-UI http://www.material-ui.com/ and receive the following errors during the build process:

ERROR in ./~/react-addons-transition-group/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactTransitionGroup' in c:\code\TDC\preact\node_modules\react-addons-transition-group
 @ ./~/react-addons-transition-group/index.js 1:17-58

ERROR in ./~/react-addons-create-fragment/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactFragment' in c:\code\TDC\preact\node_modules\react-addons-create-fragment
 @ ./~/react-addons-create-fragment/index.js 1:17-51

Is this something that is common working with controls built for React?

**Comment by developit** [comment]
Hi @struckm! 

For the CSSTransitionGroup you should just be able to alias it to [preact-css-transition-group](https://github.com/developit/preact-css-transition-group).  

For CreateFragment, I actually haven't encountered that one yet! I'll take a look at what it does, likely just something we need to shim.

**Comment by struckm** [comment]
Thanks for the quick response, the alias worked for transition group but fragment is still an issue. I'm looking at pulling [Material-UI](http://www.material-ui.com/) out of the project in favor of [Material Design Lite](https://github.com/developit/preact-mdl) since those are already Preact components. Also, I would like to remove preact-compat from the project.

**Comment by developit** [comment]
That's a good goal, and it should dramatically reduce the size of your application. Feel free to drop into Gitter if you run into anything on the way!
