### ISSUE TITLE
Missing documentation for browserify config

### ISSUE THREAD

**Issue by crccheck** [developit/preact-compat#211]
The readme instructions right now are missing for browserify. There's a section: https://github.com/developit/preact-compat#usage-with-browserify but it yada-yadas over huge sections.
1. How do you order your Browserify transforms? You need to babelify it first so aliasify can parse the code, but you have to aliasify it first so browserify doesn't complain about missing packages
2. You can install react too so babel can run, but then your bundle size is the same.

**Comment by developit** [comment]
I'm not a browserify user and not familiar enough to really make a recommendation here. Installing React just to silence a warning seems a little odd, but then so does applying a code transform in order to alias dependencies (versus using a mapping during dependency resolution).
Do you have a way that works best?

**Comment by crccheck** [comment]
Searching github, it looks like I'd be the first to attempt: https://github.com/search?q=aliasify+preact-compat&type=Code

Originally, I was hoping to just try `preact` on a small project over a break, so I've moved on to other things now.

**Comment by developit** [comment]
Would this be what you were looking for?
https://github.com/ubilabs/react-geosuggest/pull/103/files

**Comment by crccheck** [comment]
That's what I tried with "2. You can install react too so babel can run, but then your bundle size is the same." But I didn't run it through uglify yet. I'll try that.

**Comment by developit** [comment]
@crccheck are the instructions on the official preact site any clearer? They are more recent:
https://preactjs.com/guide/switching-to-preact#aliasing-via-browserify

**Comment by crccheck** [comment]
I saw that, and it looks to me like they just took your instructions :tada: 

After running uglify, my minified + gzip output went from 212K to 156K. So the keys to using this this browserify seems to be:

1. use the `aliasify` transform after `babelify`
2. you have to keep `react` and `react-dom` installed
3. there aren't any results until you minify your code

NOTE: My app seems to still work, but I haven't dug into how it's still working.

**Comment by developit** [comment]
That's pretty decent in terms of a size drop!  I just helped someone else out with a browserify-related query and it lead me to this lovely plugin you may want to try - he had ended up with multiple copies of some dependencies (including preact) in his bundle, and this fixed it perfectly:

https://www.npmjs.com/package/browserify-resolutions

```sh
browserify -p [browserify-resolutions '*'] ...etc
```

**Comment by crccheck** [comment]
nice. I tried the `rollupify` transform but that fails with a catch-22 with jsx. I'll have to dig further into everything another day. I just heard about preact and I'm eager to use it, but I have some React components I want to reuse.

**Comment by developit** [comment]
rollupify should be pretty awesome yeah. we're using rollup to make the builds for preact and preact-compat as tiny as possible already.

**Comment by marvinhagemeister** [comment]
If anybody is using `browserify` please add the necessary instructions to [our docs](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact).
