### ISSUE TITLE
Uncaught TypeError: PropTypes.instanceOf is not a function with webpack-2.1.0-beta.4

### ISSUE THREAD

**Issue by bhavinkamani** [developit/preact-compat#22]
I tried to convert a a very simple react App with preact-compat. I am getting following error while doing so.
```
Uncaught TypeError: PropTypes.instanceOf is not a function
```
I have uploaded the [repo](https://github.com/bhavinkamani/webpack_demo) for ref. 

It is complaining about PropTypes used for Redbox component used within webpack. So it seems to be at a conflict with Webpack. BTW I am using `webpack 2.1.0-beta.4`. Is there something that I am missing at my end.

**Comment by developit** [comment]
@bhavinkamani This is a bug in Webpack 2, introduced in `2.1.0-beta0`.
The commit to Webpack that broke it is [here](https://github.com/webpack/webpack/commit/902220a0ea51cbd1c117ff274238eb184131b99f).

I have opened an issue at webpack/webpack#2162, we can track progress there.

Cheers!

**Comment by bhavinkamani** [comment]
Thank you very much.

**Comment by developit** [comment]
No problem! I'll be following your project so I can keep up to date, your build setup looks really interesting.  I've been playing around with Webpack 2 a fair bit myself, running into all sorts of strange things.

**Comment by bhavinkamani** [comment]
Yep. i have been enjoying my time setting up webpack. What you are doing is incredible. Thank you for your contribution.
