### ISSUE TITLE
Cannot resolve module 'preact-compat/lib/ReactInputSelection'

### ISSUE THREAD

**Issue by fend25** [developit/preact-compat#226]
Hi! Thakes for the great (and tiny) library!
I found one more needed React-lib module, not existing in preact-compat:

ERROR in ./~/react-maskedinput/lib/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/ReactInputSelection' in C:~~~\node_modules\react-maskedinput\lib
 @ ./~/react-maskedinput/lib/index.js 9:15-55

**Comment by marvinhagemeister** [comment]
Closing because of inactive. Feel free to ping us if the issue remains with Preact X.
