### ISSUE TITLE
Support for replaceState

### ISSUE THREAD

**Issue by addyosmani** [developit/preact-compat#227]
It appears [replaceState](https://facebook.github.io/react/docs/component-api.html#replacestate) is [confirmed](https://twitter.com/_developit/status/787992963771084801) as missing from preact-compat. Would be awesome to consider implementing it.

This is currently breaking a [Preact port](https://github.com/addyosmani/preact-hn/issues/4) of a React Hacker News app I work on.

**Comment by developit** [comment]
Definitely top of the list, should also be a pretty quick fix. PRs welcome!

**Comment by developit** [comment]
Support for replaceState is available in [3.9.0](https://github.com/developit/preact-compat/releases/tag/3.9.0).

**Comment by addyosmani** [comment]
![7782b99e033f1f6314b68a823d80f8a6e285e0e12204664ef66a30bed256f617](https://cloud.githubusercontent.com/assets/110953/19651569/4003936c-99c2-11e6-9961-5dd52a3fc4b9.jpg)
