### ISSUE TITLE
Compatibility in node

### ISSUE THREAD

**Issue by impronunciable** [developit/preact-compat#23]
Hi, I'm trying to use this in node for using react components and then server-side rendering the preact components. Is that possible?

**Comment by developit** [comment]
@impronunciable yes, rendering to HTML in Node is possible using [preact-render-to-string](https://github.com/developit/preact-render-to-string).

**Comment by impronunciable** [comment]
@developit I know but when I try to use a react module it asks for react and I'm trying to use the same modules both for the front-end and the back-end

btw keep with the awesome work, preact rocks!

**Comment by developit** [comment]
You'll need to alias React and React-dom as `preact-compat`  for this I tend to use Webpack and bundle, even targeting node.

**Comment by impronunciable** [comment]
@developit Oh, I thought the webpack config will work only for the front-end. Thanks!

**Comment by developit** [comment]
Should work for both, just make sure to use the render function from render-to-string. I might throw together a quick Express demo in a bit.

**Comment by impronunciable** [comment]
Cool, thanks.
I'm already using preact-render-to-string and it's working like a charm
