### ISSUE TITLE
React DnD renders as <undefined></undefined>

### ISSUE THREAD

**Issue by adjohnston** [developit/preact-compat#232]
I am attempting to use React DnD with Preact Compat but running into an issue of the `DragDropContext` component rendering as `<undefined></undefined>`.

My node environment is currently set to v5.5.0. I am using JSPM as my package manager. Once I switched over to React it did work as planned.

I have put together a mocked project that replicates the problem. The repo can be found here. https://github.com/adjohnston/preact-dnd.

Here's a breakdown of the files themselves, plus a screenshot of the issue from the browser.

**Index**

```
import React, { createClass } from 'react'
import { render } from 'react-dom'
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import DragArea from 'js/drag-area'

const App = createClass({
  render() {
    return (
      <div>
        <p>
          The component below will not be rendered correctly. Instead it will render as: <pre><code>&lt;undefined>&lt;/undefined></code></pre>
        </p>

        <DragArea />
      </div>
    )
  }
})

render(<App />, document.querySelector('#app'))
```

**Drag Area**

```
import React, { createClass } from 'react'
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import Card from './card'

const DragArea = createClass({
  render() {
    return (
      <div>
        <Card />
        <Card />
      </div>
    )
  }
})

export default DragDropContext(HTML5Backend)(DragArea)
```

**Card**

```
import React, { createClass } from 'react'
import { DragSource } from 'react-dnd'

const type = 'card'

const cardSource = {
  beginDrag() {
    return {}
  }
}

const collect = connect => {
  connectDragSource: connect.dragSource()
}

const Card = createClass({
  render() {
    return this.props.connectDragSource(
      <div>
        Card
      </div>
    )
  }
})

export default DragSource(type, cardSource, collect)(Card)
```

![image](https://cloud.githubusercontent.com/assets/666676/19804779/611135fc-9d08-11e6-945a-85e3d15d9fcd.png)

Any help in solving the issue would be greatly appreciated.

**Comment by developit** [comment]
Hi @adjohnston - I am trying to install your repro but it's failing on `jspm install`. I've never used JSPM, not sure what to make of the error:
<img width="542" alt="screen shot 2016-10-28 at 8 09 20 am" src="https://cloud.githubusercontent.com/assets/105127/19806003/dd7a97f0-9ce5-11e6-92b8-c70da5ae5f85.png">

**Comment by adjohnston** [comment]
Oh that's quite interesting. Are you able to `jspm install npm:react-dnd` separately?

**Comment by developit** [comment]
No :( I do have a custom npm registry on this computer, might be the issue. Will try tonight on another one.

**Comment by adjohnston** [comment]
I did another setup with Webpack and I think this may actually be an issue with JSPM. I added a branch with my Webpack implementation _(my Webpack knowledge is limited)_ but it looks to be working for me.

**Comment by developit** [comment]
@adjohnston The DnD issue you saw might be caused by JSPM? Or the install failure I was seeing?

**Comment by adjohnston** [comment]
I actually believe it's an issue with JSPM. I will try and dig a little deeper to see why but I am no more an expert with JSPM as I am Webpack.

**Comment by developit** [comment]
you and me both! lol

**Comment by adjohnston** [comment]
Would you like me to close the issue?

**Comment by developit** [comment]
Up to you - I still need to take a look at your webpack branch but if you're saying React-DnD works fine on that branch I'm thinking maybe we can migrate this to JSPM?

**Comment by adjohnston** [comment]
Yeah, you're more than welcome to take a look. If you want to satisfy your own curiosity haha

**Comment by rossPatton** [comment]
i am having this issue, but with my entire app, and only when run in production mode. when I run my app in development mode, everything works fine

I am using `react-dom/server` renderToString on the server side and `preact-compat` on the client side. I am using webpack, not jspm

![screen shot 2017-04-13 at 1 29 12 pm](https://cloud.githubusercontent.com/assets/2379901/25016208/088b78ac-204d-11e7-83d1-17f0a8f63b60.png)

Any ideas?

**Comment by developit** [comment]
@rossPatton are you getting `<undefined>` in your server-render, or your client render?  This is almost always caused by one of two things:
1. a broken React alias (trying to render React elements with Preact or the other way around)
2. named VS default imports (`import { Thing }` instead of `import Thing` which means it's undefined).

Feel free to drop into the Preact slack if you are able to provide more context - https://preact-slack.now.sh

**Comment by nehaabrol87** [comment]
@rossPatton I am having the exact same issue only in production mode. Curious how did you solve your problem?
