### ISSUE TITLE
Preact calls onChange handler when using dispatchEvent while React does not

### ISSUE THREAD

**Issue by linde12** [developit/preact-compat#237]
Hello!

For one of my projects i'm using a library which, in the onChange handler, uses `dispatchEvent` to dispatch a `change` event on the changed element. This works fine with React since React doesn't call callbacks when the event was dispatched via `dispatchEvent`. However Preact seems to call it's onChange handler even when the event was triggered by `dispatchEvent`. This causes an infinite loop which in turn causes `Uncaught RangeError: Maximum call stack size exceeded.`

An example:

```
import React, {Component, PropTypes} from 'react';

class App extends Component {
  constructor () {
    super();
    this.state = {val: ''};
    this.onChange = this.onChange.bind(this);
  }
  onChange (evt) { // This will be called recursively with Preact while with React it will only be called once per change
    this.setState({val: evt.target.value});
    console.log('Changed!');
    evt.target.dispatchEvent(new Event('change', {
      bubbles: true,
      cancelable: true
    }));
  }
  render () {
    return (
      <div>
        <input type="text" onChange={this.onChange} value={this.state.val}/>
      </div>
    );
  }
}
```

When having `react` & `react-dom` aliased as `preact-compat` this will throw an exception. If you comment out the aliases so that React is used then there is no error and the code works as expected.

I will try to look into this to find out where it happens but i would appreciate some help from someone who have more experience with the code-base

**Comment by linde12** [comment]
To me it seems that React adds an `oninput` listener to textfields when a user specifies onChange events on them instead of adding `onchange` listeners(See: https://github.com/facebook/react/blob/e3131c1d55d6695c2f0966379535f88b813f912b/src/renderers/dom/shared/eventPlugins/ChangeEventPlugin.js)

So i'm guessing something similar should be done with Preact?

**Comment by linde12** [comment]
I did something like this:

```
-    name = toLowerCase(name.substring(2));
+    if (name === 'onChange' && node.nodeName === 'INPUT' || node.nodeName === 'TEXTAREA') {
+      // onchange -> oninput if node == input/textarea
+      name = 'input';
+    } else {
+      name = toLowerCase(name.substring(2));
+    }
```

and it works for my use case. React did some browser-compat checking before which is a good idea.

**Comment by developit** [comment]
Hi @linde12 - looks like we'll want to do that transformation, yup. Want to submit the PR, or should I add you as a reviewer on one?

**Comment by linde12** [comment]
Hey!

If you have time it'd be nice if 

I wouldn't mind throwing up a PR but i'm this diff doesn't contain any backwards-compatible solution. IE9 doesn't fully support the input event even if it claims so, and i guess you want to keep on supporting it.

If you're fine with the way it is now or want to add some code to make it IE9-compatible then i'd be happy to review!

Tell me if you're busy and i'll have a look as soon as i get some more time!

**Comment by developit** [comment]
Open to suggestions here!

**Comment by linde12** [comment]
The above should work but IE9 doesn't properly fire the `input` event when removing text. Instead it fires `selectionchange`. So if we have some polyfill for `input` i think the above should work fine for IE9 as well

**Comment by marvinhagemeister** [comment]
I don't think there is a way around that. Preact intentionally relies on the browser's event system. That's one of the key differences between Preact and React.
