### ISSUE TITLE
Issue with transform-react-inline-elements

### ISSUE THREAD

**Issue by tleunen** [developit/preact-compat#238]
When I use preact with `babel-plugin-transform-react-inline-elements`, my root element is `undefined`. The issue is not there with React.

Any idea why? I don't have any errors in the debugger.

Unfortunately I have this issue in a private project, but the project is a small component rendering a redux provider with a connected component as a child.

**Comment by developit** [comment]
Hi @tleunen - I don't think `preact-compat` is compatible with that plugin. For what it's worth, there is essentially no performance advantage of using it with preact.  I would suggest disabling it if you can.

**Comment by tleunen** [comment]
Yes, I actually checked the gzip size after the build and it was the same.

Even babel-runtime produce a bigger filesize. Anyway, removing all this. Thanks for the quick confirmation :)

**Comment by developit** [comment]
No problem! I'll close this out then I guess 😀

**Comment by tleunen** [comment]
yep sorry, doing it now ;)
