### ISSUE TITLE
Whats the difference between preact and preact-compact

### ISSUE THREAD

**Issue by SunnyGurnani** [developit/preact-compat#245]
Does using preact-compact increase the bundle size compared to using preact alone ?

If it does increase how much is the impact ?

**Comment by developit** [comment]
Yes, absolutely. Combined I believe they are somewhere around 5kb gzipped?  There are a lot of "internal" or deprecated React APIs that `preact-compat` has to emulate on top of preact itself.

If you're starting a new project, I'd recommend avoiding `preact-compat` in your own codebase, and simply keeping the alias handy for third-party dependencies.  If you don't end up needing it, you'll be saving yourself a bit of size!

**Comment by cia48621793** [comment]
preact-compact is the wrapper for ReactJS to preact. Just like Wine, who translates WinAPI into POSIX, preact-compact translates `React.createElement` into `h` or even `React.Component` into `Component`. Then we can reuse existing React libraries, reduce the size of client bundle and (unlikely) to get better performance

**Comment by developit** [comment]
@cia48621793 That's actually a pretty good analogy haha. Closing this out since I think we've answered.
