### ISSUE TITLE
Fluxible Router Not Working With Preact (constructor.prototype methods missing)

### ISSUE THREAD

**Issue by chrishinrichs** [developit/preact-compat#248]
Fluxible uses this pattern in a few places where they use `React.createClass` to instantiate a class and then expect `this.constructor.prototype` to contain all of the methods that were passed. It appears that Preact doesn't add these methods to the prototype the way React does - would that be difficult to change? Here is an example where a JS error occurs in fluxible router:

https://github.com/yahoo/fluxible/blob/master/packages/fluxible-router/lib/createNavLinkComponent.js#L97

**Comment by developit** [comment]
Seems like something we could do. The methods wouldn't be bound yet, but we could certainly copy them into the prototype at creation time.  This seems at least somewhat related to #240.
