### ISSUE TITLE
Process checking adds .56 KB (gzip) to bundle in Webpack build

### ISSUE THREAD

**Issue by insin** [developit/preact-compat#252]
The way the `DEV` variable is set leaves hanging references to `process` when running the standard sort of Webpack production build where `process.env.NODE_ENV` is replaced with '"production"' to allow dead-code elimination to strip dev-only code out of your build., so Webpack pulls in a `process` shim.

```js
const DEV = typeof process==='undefined' || !process.env || process.env.NODE_ENV!=='production';
```

If you add `node: {process: false}` to your Webpack config to prevent this, the propType checking code this variable guards will be present and active in production.

Some numbers from building [this app](https://github.com/insin/react-tesla-range-calculator) with `nwb build-react-app --preact`:

Initial build:
```
dist\app.c3442091.js   12.88 KB
```

With `node: {process: false}` in Webpack config:
```
dist\app.90f4cb52.js   12.34 KB
```

If instead of configuring Webpack I go and change the above line to `const DEV = process.env.NODE_ENV!=='production';` in `node_modules/preact-compat/dist/preact-compat.js`
```
dist\app.e35e7d18.js   12.32 KB
```

**Comment by developit** [comment]
Does this work when not bundled via webpack though?

**Comment by developit** [comment]
@insin I'm thinking it's better to switch to this:

```js
let DEV = true;
try {
	if (process.env.NODE_ENV==='production') DEV = false;
}
catch (e) {}
```

Let me know if that looks like it might cause issues to you.

**Comment by lukeed** [comment]
Related: #403

**Comment by marvinhagemeister** [comment]
This is fixed in `master`.
