### ISSUE TITLE
ModuleNotFoundError in react-addons-update

### ISSUE THREAD

**Issue by sudodoki** [developit/preact-compat#260]
Using 
```
alias: {
            'react': 'preact-compat',
            'react-dom': 'preact-compat'
        }
```
in existing react app, I get
```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'preact-compat/lib/update' in %some-long-path-here%/node_modules/react-addons-update
```
I'm using react@15.1.0 and react-addons-update@15.1.0.
Do you happen to know whether there's a fix to this issue?

**Comment by nilssonan** [comment]
Having the same problem!

**Comment by developit** [comment]
`react-addons-update` is another one of the React internal libs people hotlinked without thinking 👎 
It's just a module that points back into the react source, you can see the real code here:
https://unpkg.com/react@15.4.2/lib/update

We'll need to replicate it in `preact-compat`, which is pretty annoying given it has nothing to do with React at all.

**Comment by halfninja** [comment]
`react-addons-update` has been superceded by a drop-in replacement `immutability-helper`, so you could add an alias to that in your build.

**Comment by developit** [comment]
Yes, also I should add that `immutability-helper` is amazing and everyone should give it a read-through!
