### ISSUE TITLE
Add support for defaultValue

### ISSUE THREAD

**Issue by aem** [developit/preact-compat#261]
When trying to use the `defaultValue` prop on a `<textarea />`, the textarea shows up blank. This works with React but not when using a webpack alias to preact-compact. Changing the prop to `value` instead of `defaultValue` is a workaround but the `defaultValue` prop should be supported. Reproducible on `preact-compat@3.9.4` with `preact@7.1.0`

**Comment by developit** [comment]
Sorry for the no-reply there! We'll have to patch support for that in for sure.

**Comment by gholtslander-va** [comment]
Ahh, I'm having the same problem with `select` fields right now...

**Comment by developit** [comment]
@gholtslander-va `defaultValue` not being applied?

**Comment by gholtslander-va** [comment]
Yeah, in the case of a select box it just has the top option selected, as though the "value" was empty.

**Comment by developit** [comment]
@gholtslander-va good to know, we can prioritize this. I added a fix above but it'd be best to fix it in `preact-compat` itself.

**Comment by gholtslander-va** [comment]
I have some time right now and was hoping to take a look. Cool.

**Comment by developit** [comment]
There are a bunch of preact people in the Slack, might be good for you to join there if you're implementing things 👍 https://preact-slack.now.sh
