### ISSUE TITLE
React.Children helpers should iterate over children inside an iterator

### ISSUE THREAD

**Issue by neeharv** [developit/preact-compat#262]
The behaviour defined for React.Children.<forEach/map> is to iterate recursively over the children (at least for one level), so if the children contain an iterable, that's iterated over and the iterator function is called for those

```jsx
// This is what happens in React
children = [<Component1 />, <Component2 />, [<Component3/>, <Component4 />]
React.Children.forEach(children, (child) => console.log(child));
// All 4 Components are printed
```

This is done to allow patterns like
```jsx
<RootComponent>
  <Component 1 />
  <Component 2/>
  {[1, 2].map(_ => <Component3 />}
</RootComponent>
```

With preact-compat, since the iterator just does a pass through, this causes a difference in behaviour that breaks for libraries. For eg - https://github.com/neeharv/react-tabs/blob/master/src/helpers/childrenPropType.js#L30

Since it's a passthrough, the data structure passed is `[Vnode, Vnode, Array]` for the above example, and `child.type.displayName` bombs for the Array

**Comment by developit** [comment]
@neeharv In Preact (and thus preact-compat), nested Arrays from JSX are flattened at the time of instantiation: https://github.com/developit/preact/blob/master/src/h.js#L28-L30

I'm not sure how you're ending up with an unflattened `props.children`. Are you able to elaborate on that?

**Comment by neeharv** [comment]
@developit ah, I see the problem. React allows iteration over any data structure that implements the `iterable` protocol, not just Arrays. So in my use case, I was using `Immutable.List` and mapping over that to render children. Looks like that is why it isn't flattened. Should I open a PR to fix this? Should be a simple one.

**Comment by developit** [comment]
Ah that makes sense. Preact doesn't currently support Immutable. If you have an idea of how to start on support for it, I'd love to see if we could get that into preact itself! There is an issue for Immutable support here: developit/preact#282

**Comment by marvinhagemeister** [comment]
Yup, that's true. We currently only support arrays as children. Adding support for the iterable protocol would need to be done in core instead of compat.
