### ISSUE TITLE
Breaks onDoubleClick mouse event.

### ISSUE THREAD

**Issue by rokoroku** [developit/preact-compat#264]
Using ``preact-compat`` as an alias for ``react`` and ``react-dom`` seems to break some mouse events. 

for example, ``onChange`` inside of ``<input type="checkbox">`` fired twice, and ``onDoubleClick`` inside ``<label>`` are not fired.

Issue can be reproduced with this sample: [link](https://github.com/rokoroku/typescript-react-redux-boilerplate/tree/302b1fa3a79d72e8909b7012d096b83b1f661fd1)

**Comment by developit** [comment]
The event name is actually `onDblClick`. Are you able to verify that `onDoubleClick` works in React? If so we can just alias that event name. 

As for the onChange event, I believe we already merged a PR that fixes the doubling issue, but it hasn't yet been released.

**Comment by rokoroku** [comment]
@developit I just can see ``OnDoubleClick`` from documentation. See [documentation#mouse-events](https://facebook.github.io/react/docs/events.html#mouse-events)

**Comment by developit** [comment]
Alright! Open to PRs, or I'll try to get this done when I'm back to things next week!
