### ISSUE TITLE
Select field `onChange` fires twice.

### ISSUE THREAD

**Issue by shanewwarren** [developit/preact-compat#279]
Hey there!

JSFiddle reproducing the issue: (check the console output)
[https://jsfiddle.net/shanewwarren/08stgkap/](https://jsfiddle.net/shanewwarren/08stgkap/)

Basically, I'm noticing that given a very simple `select` component example is still dispatching two events for the `onChange` event.

I saw this was addressed previously here: [#160](https://github.com/developit/preact-compat/issues/160) and [#20](https://github.com/developit/preact-compat/issues/20).

However, it seems to still be an issue.

If you'd like me to dig deeper please let me know!

Thanks!

**Comment by developit** [comment]
Hi @shanewwarren! Looks like the [fix](https://github.com/developit/preact-compat/commit/9e926ca93b3a23f3009b5af84667e811ef99fc4c) just hasn't been released yet.

**Comment by developit** [comment]
Fixed as of `preact-compat@3.10.0`:
![91ef6eacb472e64c0072039b4d9c6f3a](https://cloud.githubusercontent.com/assets/105127/21871457/35fce132-d830-11e6-9275-4ea574c20ca2.gif)
