### ISSUE TITLE
Publish to CDN JS

### ISSUE THREAD

**Issue by mohsen1** [developit/preact-compat#281]
Would be nice to require Preact-compat from CDN

**Comment by developit** [comment]
Hmm! yes you're right! Preact itself is up there, but preact-compat isn't.
For what it's worth, all Preact modules are published so that they work nicely with `unpkg.com` too, so while we're getting -compat onto CDNJS, you can do:

```html
<!-- UMD bundle: -->
<script src="//unpkg.com/preact-compat@3.9.4"></script>

<!-- UMD bundle, minified: -->
<script src="//unpkg.com/preact-compat@3.9.4/dist/preact-compat.min.js"></script>
```

**Comment by mohsen1** [comment]
I'm happy to help with this but per CDNJS PR template they prefer the author to open the PR.

As for `unpkg.com` we can't use them in production. We have to use official CloudFlare endpoints since we're paying them.

**Comment by fokusferit** [comment]
This has been done and can be closed :) 

(preact-compat)[https://cdnjs.com/libraries/preact-compat]
