### ISSUE TITLE
Documentation is missing to avoid shipping proptypes in production mode

### ISSUE THREAD

**Issue by 0xR** [developit/preact-compat#285]
Since Preact users are sensitive to bundle size it is not great that the `proptypes` lib are bundled even in production mode. A note in the README on how to avoid shipping `proptypes` in a production build would be great.

Currently I can't submit a PR, but it probably involves setting something like the ignorePlugin: https://webpack.github.io/docs/list-of-plugins.html#ignoreplugin

**Comment by developit** [comment]
A PR would be great! I've done the stripping before, but it's a little tricky since things import `proptypes` and call methods on it.  Another option that might be interesting to explore would be having a `proptypes-disabled` module (or `proptypes/disabled`) [like this snippet](https://github.com/developit/preact-redux/blob/master/src/compat.js#L12-L16) that exports only empty functions which can then be easily stripped out via Dead Code Elimination.

**Comment by 0xR** [comment]
Things other than `preact-compat` itself? I figured it was a single import which should be a no-op.

**Comment by developit** [comment]
True, I guess if nothing references the object. Just most React third party libs do use PropTypes, stripping that out is possible, but slightly difficult.

**Comment by 0xR** [comment]
I just tried it out and I have it working on my machine. What I did was add this plugin to my production webpack config:
```
  new webpack.NormalModuleReplacementPlugin(/^proptypes$/, path.resolve(__dirname, 'proptypes-disabled.js')),
```

And have a file `proptype-disabled.js` containing: 
```https://github.com/lerna/lerna
function productionTypeChecker() {
}

productionTypeChecker.isRequired = productionTypeChecker;
const getProductionTypeChecker = () => productionTypeChecker;
export default {
  array: productionTypeChecker,
  bool: productionTypeChecker,
  func: productionTypeChecker,
  number: productionTypeChecker,
  object: productionTypeChecker,
  string: productionTypeChecker,
  symbol: productionTypeChecker,

  any: productionTypeChecker,
  arrayOf: getProductionTypeChecker,
  element: productionTypeChecker,
  instanceOf: getProductionTypeChecker,
  node: productionTypeChecker,
  objectOf: getProductionTypeChecker,
  oneOf: getProductionTypeChecker,
  oneOfType: getProductionTypeChecker,
  shape: getProductionTypeChecker,
};
```

Which is based on: https://github.com/facebook/react/blob/master/src/isomorphic/classic/types/ReactPropTypes.js#L95

To make this a proper solution it would be good to have a `proptypes-disabled` which should probably be published from: https://github.com/developit/proptypes . This is to make it easier to maintain since proptypes-disabled should be kept in sync with proptypes itself. To publish 2 packages from a single github repo https://github.com/lerna/lerna could be considered. 

I can't spend more company time on it for now. So anyone is free to pick this up. I don't think the fix is quite beginner level, but it should not be too hard to pick this up if someone wants to learn / contribute.

**Comment by developit** [comment]
oh wow, @0xR I'm pretty sure you just solved developit/proptypes#5 😳

**Comment by developit** [comment]
@0xR as noted by @sebmarkbage [here](https://twitter.com/sebmarkbage/status/821788096081469440), if you want to fully strip out `propTypes`, you need to also remove their usage from components via [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types).  I had forgotten this was in my builds.

**Comment by 0xR** [comment]
Unfortunately, my work was the opposite of cleanroom. I guess no1 will be
suing facebook.

The strip proptypes babel plugin is a nice future enhancement. I'll
remember it.

Op wo 18 jan. 2017 18:43 schreef Jason Miller <notifications@github.com>:

**Comment by developit** [comment]
heh, no worries. The interface is public regardless.

**Comment by kurtextrem** [comment]
Anything new? I'm using preact-compat and I'm seeing the prop-types package in my prod build (already stripping using transform-react-remove-prop-type - but Preact still imports and it and webpack adds it to the bundle automatically)

**Comment by kurtextrem** [comment]
Seems to be easily solvable today:
Add this to your Babel config (plugins):
`['transform-react-remove-prop-types', { removeImport: true, additionalLibraries: ['react-immutable-proptypes'] }]`

And this to your webpack config:
`new webpack.IgnorePlugin(/prop-types/)`
and gone it is.

**Comment by developit** [comment]
@kurtextrem exactly right. Only thing I'd change is to use the built-in disabled mode in `prop-types` - it's smaller and more compatible:

```js
resolve: {
    alias: {
         'prop-types$': 'prop-types/prop-types.min.js'
    }
}
```

**Comment by kurtextrem** [comment]
Oh nice, didn't know about that. Thank you Jason :)

**Comment by developit** [comment]
@kurtextrem ah you're right - it still does basic validation, just excludes error messaging.  Sounds like we might want to update `proptypes/disabled` to reflect the `prop-types` API.

**Comment by lukeed** [comment]
I've followed all leads here in this thread, nothing worked 😢 

* The babel plugin's `remove:true` does not strip `prop-types` from within `preact-compat`
* Aliasing `'prop-types$': 'prop-types/disabled'` doesnt work because that file doesn't exist; webpack errors out
* Aliasing to the minified file _works_ but the file is still in the bundle at the end of the day

**Comment by lukeed** [comment]
Solved!

```js
new webpack.IgnorePlugin(/prop-types$/)
```

**Comment by lukeed** [comment]
@developit This can be closed with my fix above 👆

**Comment by kurtextrem** [comment]
Are you sure? When I put the Ignore line into my build, rendering fails completely as Webpack throws an error "prop-types" not found.

**Comment by lukeed** [comment]
Sorry @kurtextrem for the super long delay 😲 

The `IgnorePlugin` has to be for production builds only -- if a library is requiring it in a production setting, that shouldn't be the case.

As for `webpack-plugin-replace`, we're using it in Preact CLI [here](https://github.com/developit/preact-cli/blob/master/src/lib/webpack/webpack-base-config.js#L232). It's actually intended to break if you don't configure it 😇
