### ISSUE TITLE
Error when trying to uglify

### ISSUE THREAD

**Issue by hanford** [developit/preact-compat#298]
When trying to uglify preact-compat I get the following error: 
```
[0] ERROR in vendor-fee180ffb09ac9880d80.js from UglifyJs
[0] SyntaxError: Unexpected token: name (VNode) [./~/preact-compat/src/index.js:41,0][vendor-fee180ffb09ac9880d80.js:66,4]
```

My uglifyjs options in webpack are:
```
  if (isProduction) {
    base.plugins = base.plugins.concat([
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          'screw_ie8': true,
          'warnings': false,
          'unused': true,
          'dead_code': true
        },
        output: {
          comments: false
        },
        sourceMap: true
      }),
      new webpack.optimize.AggressiveMergingPlugin()
    ])
  }
```

I'm using webpack 2.2, and haven't modified any of my source to follow preact, I simply did the easiest transformation and aliased `react` and `react-dom` with `preact-compat`.

After looking at the stack trace, was I supposed to import hyperscript or something? Not sure what these lines are trying to achieve. Here is a screenshot of the lines that webpack is complaining about: 
![](http://d.pr/i/kruO+)

**Comment by developit** [comment]
Hmm - it sounds like you're using Webpack 2, but not transpiling libraries.  Preact ships a `module` entrypoint, which points to the ES6 source, so you need to transpile it with `babel-loader`.  This is true for any `module` you use with Webpack 2, and has nothing to do with preact or preact-compat.

**Comment by hanford** [comment]
Thanks will investigate and likely close tomorrow.

**Comment by sbehrends** [comment]
I have the same issue using nwb :(

**Comment by mistadikay** [comment]
@sbehrends just compile `preact` using `babel-loader` (see https://github.com/developit/preact-compat/issues/155#issuecomment-242905949). Perhaps it should be clarified in README @developit?

**Comment by developit** [comment]
That's probably the minimal option, though honestly this comes up enough that I think we need to ship an ES Modules + ES5 build in dist.

**Comment by hanford** [comment]
yeah @developit, I've been under the impression that transpiling `node_modules` is typically a bad idea. However, I feel for you. One thing react + es6 + webpack has made harder is distributing packages

**Comment by developit** [comment]
It's a tradeoff.  There are some excellent reasons to transpile (doing it to first party code means `npm link` works without nested builds) and some reasons not to (weight, future compat).
