### ISSUE TITLE
undefined when rendered.

### ISSUE THREAD

**Issue by bradennapier** [developit/preact-compat#303]
Since switching my aliases to fix the bug in preact-compat / preact where it aims at /src instead of /dist all the sudden my app renders undefined

![image](https://cloud.githubusercontent.com/assets/15365418/23195388/04467fe2-f868-11e6-907c-180c5df98d5d.png)

Any ideas on what i may be doing wrong here?  I confirmed that the call to render is sending a component

**Comment by bradennapier** [comment]
'transform-react-constant-elements' was the problem - should have known

**Comment by developit** [comment]
Been bitten by this too!

**Comment by bradennapier** [comment]
Might be a good idea to put something in the documentation for switching to preact?

**Comment by developit** [comment]
Yup, wherever people would normally be looking when doing the `preact-compat` alias.
