### ISSUE TITLE
Issue with proptypes on prod

### ISSUE THREAD

**Issue by anaibol** [developit/preact-compat#32]
Hi! I am having an error while running on prod. PropTypes.js:21 Uncaught TypeError: Cannot read property 'isRequired' of undefined.

I am using my boilerplate similar to https://github.com/erikras/react-redux-universal-hot-example.
The build worked nicely with a difference of 100kb between react and preact :D. I  think you are doing a really good job with that an the compatibility.

![selection_015](https://cloud.githubusercontent.com/assets/3210177/14245809/f203fb46-fa63-11e5-9cb8-cbea7bbad4b2.png)

**Comment by developit** [comment]
Ah yes, PropTypes are removed in production mode, but maybe that's not ideal since references to them would still exist. I will swap them to instead be empty functions.

**Comment by anaibol** [comment]
Great thanks!

**Comment by developit** [comment]
@anaibol Looked into this, and I realized I was wrong - PropTypes are still exported as normal in production, so I don't think that was the issue.

However, looking at the boilerplate you linked, they use two separate Webpack configs for development and production - is it possible the aliases for `react` and `react-dom` are missing or overwritten in your production config?

**Comment by anaibol** [comment]
Mmm the issue is caused by react-router which use react proptypes, and proptypes is an empty object.
The issue is present both in dev and prod environnements.
![selection_017](https://cloud.githubusercontent.com/assets/3210177/14315637/e15e0a92-fbfe-11e5-84e5-cfbb052a17ad.png)

**Comment by developit** [comment]
Ah, sorry I had thought it was only on prod. Can you grab me the output of `npm ls --depth 0`? Curious what version of `proptypes` that's coming from.

**Comment by anaibol** [comment]
I think proptypes is not beeing intstalled with preact-compat.

npm ls --depth 0
react-redux-universal-hot-example@0.1.0 /home/anaibol/Workspace/fr
├── babel-core@6.7.4
├── babel-eslint@5.0.1
├── babel-loader@6.2.4
├── babel-plugin-react-auto-display-name@0.0.1
├── babel-plugin-react-transform@2.0.2
├── babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-react-constant-elements@6.5.0
├── babel-plugin-transform-react-inline-elements@6.6.5
├── babel-plugin-transform-react-remove-prop-types@0.2.3
├── babel-preset-custom@1.3.0
├── babel-preset-es2015@6.6.0
├── babel-preset-react@6.5.0
├── babel-preset-stage-0@6.5.0
├── babel-register@6.7.2
├── better-npm-run@0.0.8
├── classnames@2.2.3
├── compression@1.6.1
├── concurrently@2.0.0
├── css-loader@0.23.1
├── UNMET PEER DEPENDENCY eslint@2.5.3
├── eslint-loader@1.3.0
├── eslint-plugin-import@1.4.0
├── eslint-plugin-react@4.2.3
├── express@4.13.4
├── extract-text-webpack-plugin@1.0.1
├── file-loader@0.8.5
├── font-awesome@4.5.0
├── font-awesome-stylus@4.5.0 extraneous
├── html-loader@0.4.3
├── html-webpack-plugin@2.14.0
├── http-proxy@1.13.2
├── isomorphic-fetch-no-polyfill@0.0.0
├── node-sass@3.4.2
├── piping@0.3.0
├── preact@4.5.1
├── preact-compat@1.6.1
├── rc-css-transition-group@2.1.4
├── UNMET PEER DEPENDENCY react@15.0.0-rc.2
├── react-addons-css-transition-group@0.14.8
├── react-css-modules@3.7.6
├── react-dom@15.0.0-rc.2
├── react-redux@4.4.1
├── react-router@2.0.1
├── react-router-redux@4.0.0
├── react-style-normalizer@1.2.8 extraneous
├── react-transform-catch-errors@1.0.2
├── react-transform-hmr@1.0.4
├── redbox-react@1.2.2
├── redux@3.3.1
├── redux-async-connect@1.0.0-rc4
├── redux-devtools@3.1.1
├── redux-devtools-dock-monitor@1.1.0
├── redux-devtools-log-monitor@1.0.5
├── redux-form@4.2.2
├── redux-thunk@2.0.1
├── sass-loader@3.2.0
├── sass-resources-loader@1.0.2
├── scroll-behavior@0.3.3
├── serialize-javascript@1.2.0
├── serve-favicon@2.3.0
├── shallow-equals@0.0.0 extraneous
├── strip-loader@0.1.2
├── style-loader@0.13.1
├── url-loader@0.5.7
├── warning@2.1.0
├── UNMET PEER DEPENDENCY webpack@2.1.0-beta.4
├── webpack-dev-middleware@1.6.1
├── webpack-dev-server@2.0.0-beta
├── webpack-hot-middleware@2.10.0
└── webpack-isomorphic-tools@2.2.41

Installing proptypes doesn't fix that.

**Comment by anaibol** [comment]
It's like present on webpack build time but not after that

**Comment by developit** [comment]
Which version of npm are you using?

**Comment by anaibol** [comment]
3.8.3

**Comment by anaibol** [comment]
Sorry, proptypes is installed correctly with preact-compat but does not appear in "npm ls --depth 0"

**Comment by developit** [comment]
I wonder if it's possible this is an issue due to `proptypes` being a Peer Dependency...

**Comment by anaibol** [comment]
It's also a normal dependency on package.json

  "peerDependencies": {
    "preact": "^4.1.2",
    "proptypes": "^0.14.3"
  },
  "optionalDependencies": {
    "preact": "^4.1.2",
    "proptypes": "^0.14.3"
  },
  "dependencies": {
    "preact-render-to-string": "^2.0.1",
    "preact-svg": "^1.4.3",
    "proptypes": "^0.14.3"
  }

**Comment by developit** [comment]
Just to make sure - you're using Webpack 1.x, right?

**Comment by anaibol** [comment]
Mm nope, webpack v2.1.0-beta.4

**Comment by anaibol** [comment]
"The PropTypes.js in your first screenshot doesn't appear to be the one preact-compat is expecting:
https://github.com/developit/proptypes/blob/master/src/index.js"
Thats the PropTypes file of react-router that uses internally react proptypes.

**Comment by developit** [comment]
Ahh, that's probably the reason. Webpack 2 has a bug with module exports. I reported it a few weeks back:
https://github.com/webpack/webpack/issues/2162

I might be able to fix this in the PropTypes module in the meantime though, copying things onto `exports` instead of using `module.exports=`.

**Comment by anaibol** [comment]
I see.. By the way, trying to see how it works with the default boilerplate (webpack v1.*), it build's correctly but running the server ends with "Error: Cannot find module 'react'". It's an universal/isomorphic boilerplate
