### ISSUE TITLE
Does not work on mobile?

### ISSUE THREAD

**Issue by bradennapier** [developit/preact-compat#320]
I seem to be getting errors with webpack 2 when trying to load on mobile

![image](https://cloud.githubusercontent.com/assets/15365418/23742187/c7ae90e2-0460-11e7-9cc6-7d3805ff96a5.png)

It would appear that things aren't transpiled so it doesnt work.

**Comment by gogoyqj** [comment]
seem that u need use babel to translate these code to es5 - then `const` never be found

**Comment by developit** [comment]
Yup, requires babel transpilation.  I'll circumvent that as part of my fix for #321
