### ISSUE TITLE
differences between preact-compat && original react found

### ISSUE THREAD

**Issue by gogoyqj** [developit/preact-compat#322]
since using preact && preact-compat in projects，I met several problems. a reason is the differences between preact & react, i list out these i found, hope helpful.

- preact@7.1.0
- preact-compat@3.9.4

##### . props.children data structure

in preact props.children is always Array, while can be Object in react if with only child. so 
using these code to judge if only child won't work in preact.

```jsx
    this.props.children && !this.props.children.length
``` 

using insted:

```jsx
    function getOnlyChild(props) {
        var children = props.children;
        if (children) {
            if (!children.length) return children;
            if (chilldren.length === 1) return children[0];
        }
    }
```

##### . render/rerender

in preact each render/rerender may cause dom move/reorder even seems unnecessary in react.

```jsx
    componentDidMount() {
        this.namedDiv = this.refs.namedDiv
    }
    componentDidUpdate() {
        this.namedDiv = this.refs.namedDiv // required in preact or this.namedDiv target wrong if balabala changed
    }
    render() {
        return (
            <div>
                {
                    this.state.balabala ? <div></div> : null
                }
                <div ref="namedDiv"></div>
            </div>
        )
    }
```

using insted:

```jsx
    ref={(ref) => {
        this.namedDiv = ref
    }}
```

##### . lifecycle

in preact parent's componentDidUpdate trigger before child's componentDidMount [#312](https://github.com/developit/preact-compat/issues/312). 

tips: 

    avoid any dependence on tigger order of these two.

##### . setState is async

if callback depends on newState, u'd better:

```jsx
    this.setState(newState, callback)
```

**Comment by developit** [comment]
Good hunting - I think these are actually all things we can solve, though `children` is the toughest.  It's "fixed" for a few cases but perhaps not all.  I'll link here as we fix the rest :)

**Comment by otbe** [comment]
Would like to 👍 for ```props.children```. This breaks actual ```react-helmet```. For example
```
<Helmet>
   <title>Foo</title>
</Helmet>
```
gives ```Helmet expects a string as a child of <title>``` and ```props.children``` is ```[ 'Foo' ]```

Thanks!

**Comment by marvinhagemeister** [comment]
We resolved issues surrounding `props.children` with Preact X. Make sure to alias `preact/compat` instead of `preact-compat`.
