### ISSUE TITLE
dist/preact-compat.es.js missing in release 3.14.2

### ISSUE THREAD

**Issue by 0xR** [developit/preact-compat#332]
It does seem to be present in 3.14.1. Fortunately `eslint-plugin-import` was there to save the day!

**Comment by developit** [comment]
Ack! Checking into this now.

**Comment by developit** [comment]
Sorry about that - I actually spotted the env issue yesterday and wondered why it hadn't caused an error! Looks like it did haha.

Fixed and released as [3.14.3](https://github.com/developit/preact-compat/releases/tag/3.14.3).
