### ISSUE TITLE
Invalid prop `children` supplied to X, expected a single ReactElement.

### ISSUE THREAD

**Issue by slaskis** [developit/preact-compat#340]
After fixing #339 [Searchkit react components](https://github.com/searchkit/searchkit) seems to kind of work but now I get this error in the console:

```
Error: Invalid prop `children` supplied to `SearchkitProvider`, expected a single ReactElement.
    at SearchkitProvider.propsHook (preact-compat.js:542)
    at callMethod (preact-compat.js:483)
    at SearchkitProvider.render (preact-compat.js:494)
    at renderComponent (preact.js:305)
    at renderComponent (preact.js:319)
    at setComponentProps (preact.js:286)
    at buildComponentFromVNode (preact.js:375)
    at idiff (preact.js:180)
    at diff (preact.js:159)
    at render (preact.js:411)
```

I'm guessing Searchkit has some rather strict PropTypes but I don't really understand the issue.

**Comment by developit** [comment]
Any chance you're able to have it pause there and see the prop value? I'm curious if it's an Array, empty Array, or undefined

**Comment by slaskis** [comment]
Prop value seems to be a VNode?

![image](https://cloud.githubusercontent.com/assets/5991/24585378/411f643e-1789-11e7-9d32-ede45f217bbc.png)

**Comment by developit** [comment]
oh - hmmm. That's an unpatched VNode! Normally [VNodes get patched by `preact-compat`](https://github.com/developit/preact-compat/blob/master/src/index.js#L41-L56) so they include `props` and `$$typeof`.. how are you writing your JSX?

**Comment by slaskis** [comment]
Actually [this](https://gist.github.com/slaskis/615ea6c3781683ce8a9555df4f662f74) is the entire javascript right now (with the access key and search url removed). 

It's just a test using searchkit and mapbox

**Comment by zcei** [comment]
May it be, that you don't have `'create-react-class': 'preact-compat/lib/create-react-class'` in your Webpack / Babel aliases?

**Comment by marvinhagemeister** [comment]
This is very likely fixed in Preact 10. Make sure to use `preact/compat` instead of `preact-compat`
