### ISSUE TITLE
Only check proptypes at element creation like React does.

### ISSUE THREAD

**Issue by tkh44** [developit/preact-compat#348]
[React Implmentation](https://github.com/facebook/react/blob/cb585229bcc76ce35ea6d068c2510a86438798ea/src/isomorphic/classic/element/ReactElementValidator.js)

**Comment by tkh44** [comment]
I have a PR for this incoming.

**Comment by developit** [comment]
A+, this is something I just overlooked for sure.  Are you thinking just check them in the constructor?

**Comment by tkh44** [comment]
No I have them checking after the vnode is normalized. This approach's only flaw is that children propType checking does not work. I added a test and am working on it now.

**Comment by developit** [comment]
@tkh44 indeed - the `props.children` normalization happens before calling lifecycle methods. thinking we'll need to clone props and inject children when doing the proptype check.

**Comment by marvinhagemeister** [comment]
This is resolved in Preact X. Make sure to use `preact/compat` instead of `preact-compat`.
