### ISSUE TITLE
Uncaught Error: Calling PropTypes validators directly is not supported by the 'prop-types' package.

### ISSUE THREAD

**Issue by BerndWessels** [developit/preact-compat#358]
Hi

I upgraded `react-router` from `4.0.0` to `4.1.1` and it now breaks with the following error message:

`Uncaught Error: Calling PropTypes validators directly is not supported by the 'prop-types' package. Use 'PropTypes.checkPropTypes()' to call them. Read more at http://fb.me/use-check-prop-types`

Is this a `preact-compat` incompatibility issue with `react` ?

It concerns me a bit and hope there is a fix.

You can easily reproduce it with [this repo](https://github.com/BerndWessels/preact-mdc-demo)

This is somehow related to this I suppose: https://github.com/reactjs/prop-types/blob/master/README.md#difference-from-reactproptypes-development-and-production-versions

UPDATE:

I've digged a bit deeper and it seems that the problem is caused in `preact-compat.es.js` in the `propsHook` function:

```js
function propsHook(props, context) {

...

	// add proptype checking
	if (DEV) {
		var ctor = typeof this==='function' ? this : this.constructor,
			propTypes = this.propTypes || ctor.propTypes;
		if (propTypes) {
			for (var prop in propTypes) {
				if (propTypes.hasOwnProperty(prop) && typeof propTypes[prop]==='function') {
					var displayName = this$1.displayName || ctor.name;
					var err = propTypes[prop](props, prop, displayName, 'prop');
					if (err) { console.error(new Error(err.message || err)); }
				}
			}
		}
	}
```

Removing the complete block within the `if(DEV)` seems to fix it.

So it seems that `react-compat` is not compatible with the new `prop-types` anymore.

Can that be fixed? I think its important.

**Comment by conceptualitis** [comment]
I had this problem as well and the underlying issue is that pretty much every React library out there (react-router, enzyme, react-redux, etc) switched to using the new `prop-types` library instead of `React.propTypes`.

I've locked my dependencies at the version preceding these udpates and everything is fine, for now.

Using the new `prop-types` library in `preact-compat` is probably going to be the fix.

**Comment by seeden** [comment]
Please release a new version with this merge

**Comment by bradennapier** [comment]
Ugh yeah just ran into this... roadblock to the maximum!

**Comment by bradennapier** [comment]
When do you plan to release this to npm so we can use it directly?

**Comment by developit** [comment]
I can do it today.

**Comment by BerndWessels** [comment]
Please let us know here once its published, thank you.

**Comment by bradennapier** [comment]
Yep, let us know!  Thanks @developit

**Comment by developit** [comment]
The `prop-types` fix is released as [3.15.0](https://github.com/developit/preact-compat/releases/tag/3.15.0).

**Comment by alayor** [comment]
I'm having this same issue when using `react-datepicker`component. (https://hacker0x01.github.io/react-datepicker/).

How can I solve it?

**Comment by conceptualitis** [comment]
@alayor you might be using a version of `react-datepicker` that predates the switch to the `prop-types` library. It looks like that happened in `0.46.0`.
