### ISSUE TITLE
How do I build this

### ISSUE THREAD

**Issue by bradennapier** [developit/preact-compat#363]
Since this no longer works in the npm version iam trying to figure out how to just build it from master so i can actually get my app working again... it broke due to prop types not working with anything new.  When I try to download and run i get a shit load of errors by default... what do i need to do on top of downloading and running it?

**Comment by bradennapier** [comment]
ERROR in ./test/svg.js
Module parse failed: /home/ubuntu/workspace/node_modules/preact-compat/test/svg.js Unexpected token (24:3)
You may need an appropriate loader to handle this file type.

ERROR in ./test/lib/ReactFragment.js
Module parse failed: /home/ubuntu/workspace/node_modules/preact-compat/test/lib/ReactFragment.js Unexpected token (11:16)
You may need an appropriate loader to handle this file type.

ERROR in ./test/jsx.js
Module parse failed: /home/ubuntu/workspace/node_modules/preact-compat/test/jsx.js Unexpected token (7:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:3)

ERROR in ./test/index.js
Module parse failed: /home/ubuntu/workspace/node_modules/preact-compat/test/index.js Unexpected token (20:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (20:10)

**Comment by developit** [comment]
How are you installing?  It should just be:

```js
git clone ...
cd preact-compat
npm install
npm run build
```

**Comment by bradennapier** [comment]
It actually builds - just the tests fail.

**Comment by developit** [comment]
Tests are fixed now on master, `prop-types` fix is released as [3.15.0](https://github.com/developit/preact-compat/releases/tag/3.15.0).
