### ISSUE TITLE
react vs preact difference for children

### ISSUE THREAD

**Issue by seeden** [developit/preact-compat#366]
I created library react-form-controlled where I am using children.props.children. Everything is working fine but not in preact because props.children does not exists for basic elements like div/span. Instead of props.children I can see just children as you can see on the next images.

React
![React](http://i.imgur.com/SimDBcJ.png)

Preact
![Preact](http://i.imgur.com/j3W1VBi.png)

**Comment by developit** [comment]
Hmm - `props.children` is there, it's just an Array because `props.children` is always an Array in Preact.

FWIW, it looks like you're already using `preact-compat` - if you change your component to inherit from preact-compat's `Component` class, `props.children` will be normalized to behave like React.

**Comment by seeden** [comment]
Vnode.props.children does not exists as you can see on the preact image. Vnode.children exists and I am fine with array but Vnode.props.children is missing.

**Comment by developit** [comment]
Ah, sorry I missed that.  What type of component is this?

**Comment by seeden** [comment]
it is standard span element but I am traversing it in Form component. I can see same buggy behaviour for all standard elements like input, fieldset, select ...

**Comment by developit** [comment]
I meant the Form component - is it a pure functional component? If not, does it inherit from preact.Component or preact-compat.Component?

**Comment by seeden** [comment]
I am using next alias in webpack:

      react: 'preact-compat/dist/preact-compat',
      'react-dom/server': 'preact-compat/server',
      'react-dom': 'preact-compat/dist/preact-compat',

```js
import { Component } from 'react';
```

**Comment by seeden** [comment]
preact-compat version is 3.15.0 and preact is 8.1.0

**Comment by developit** [comment]
Hmm - I just created a jsfiddle with those versions to test, and I'm seeing `props.children`:
<img width="287" alt="screen shot 2017-04-20 at 1 30 59 pm" src="https://cloud.githubusercontent.com/assets/105127/25244179/ade9c44a-25cd-11e7-9036-62f6686e65a9.png">

https://jsfiddle.net/developit/kL2uuzse/

This makes me wonder if you're somehow getting React VNodes somehow - `preact-compat` actually tries to deal with them by normalizing, but maybe that could cause an issue like this?

We can test - what do you get when you `console.log(<span>foo</span>)`?

**Comment by ustccjw** [comment]
i found props.children is not exist when didmount. so we will check lifecycle vnode changes.

**Comment by paranoidjk** [comment]
As we can see in https://jsfiddle.net/developit/kL2uuzse/

If used preact-compat, in single children element condition， `props.children = Object.assign({}, props.children[0], {0: props.children[0]})`

Looks weird, I think should deleted attribute `0`

**Comment by marvinhagemeister** [comment]
This is resolved in Preact X. Make sure to alias `preact/compat` instead of `preact-compat`.
