### ISSUE TITLE
Can't resolve react-dom/lib/EventPluginHub

### ISSUE THREAD

**Issue by screendriver** [developit/preact-compat#368]
I want to use [material-ui](https://github.com/callemall/material-ui). Therefore you have to use [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin).

I'm using `preact-compat` for this and my `webpack.config.js` looks like

```js
"resolve": {
    "alias": {
      "react": "preact-compat",
      "react-dom": "preact-compat"
    }
  }
```

Unfortunately my build throws following error

```sh
ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' in '/Users/me/development/foo/node_modules/react-tap-event-plugin/src'
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-41'
```

**Comment by developit** [comment]
Alias `react-tap-event-plugin` to [preact-tap-event-plugin](https://github.com/developit/preact-tap-event-plugin).  Let me know if that works.

**Comment by screendriver** [comment]
Awesome! 💃  I totally oversight that! It works out of the box. Thank you Jason 👍
