### ISSUE TITLE
Children with `dangerouslySetInnerHTML` disappear after setState

### ISSUE THREAD

**Issue by jt3k** [developit/preact-compat#371]
I found a bug with `dangerouslySetInnerHTML`

I tried to reproduce it here:

- [with React 15.1.0](https://jsbin.com/kupefof/edit)
- [with preact-compat 3.18.0](https://jsbin.com/kepukuc/edit) — bug

We see difference in the rendering of children between React and preact-compat

---
_in preact example i also used preact v8.1.0 and proptypes v1.0.0_

**Comment by developit** [comment]
Thanks for the report!

**Comment by simonjoom** [comment]
yeah i have got the same problem,
on one component i could get around to pass the dangerouslySetInnerHTML in the last children;


But for one component (one popover react with a state) this behavior stuck me. 
I really need to pass it in children of my jsx component.. 
So for now react not rendered my dangerouslySetInnerHTML because he is not in the last children of the tree.
When can you think preact-compat dangerouslySetInnerHTML  will be correctly programmed ?

I was with react-lite before, for sure preact is smaller .. but...
Thanks

**Comment by simonjoom** [comment]
OK i found the problem this night:
I'm not exactly understand what i'm doing it but after many research , i found a trick code change to pass this issue;


So the developper of preact will find faster a better update.

I tested with 2 different component (one changing state inside his child, an other from his parent)
the bug happen for
<Compjsx
myprops={myprops}
>
<div>
            <h3 className="popover-title">{popOverTitle}</h3>
            <div className="popover-content" dangerouslySetInnerHTML={{__html: "<div>" + popOverContent + "</div>"}}/>
</div>
</Compjsx>

in this example popOverContent is a var in state changing from "" to "something"


Now the code to be changed

In innerDiff:
this piece of code do this bug happen
in line 197 of preact.js
--
      else if (!child && min < childrenLen) for (j = min; j < childrenLen; j++) {
        if (void 0 !== children[j] && isSameNodeType(c = children[j], vchild, isHydrating)) {
          child = c;
          children[j] = void 0;
          
          if (j === childrenLen - 1) childrenLen--;
          if (j === min) min++;
          break;
        }
      }

if i commented all this code then i see my dangerouslySetInnerHTML rendered! .. but sure the complete thing was buggy .


so i decided to find the best fit to have all things works for a innerHTML in children of a jsx component.

here what i did 

line 168 
change to ;
      innerDiffNode(out, vchildren, context, mountAll, hydrating, null != props.dangerouslySetInnerHTML || null != props.inHTML);

line 174: (add innerHTML in other prop of the function)
  function innerDiffNode(dom, vchildren, context, mountAll, isHydrating, InnerHTML) {

finally do a test to pass the bad code for a component with a children include with a dangerouslySetInnerHTML 
      else if (!InnerHTML && !child && min < childrenLen) for (j = min; j < childrenLen; j++) {
        if (void 0 !== children[j] && isSameNodeType(c = children[j], vchild, isHydrating)) {
          child = c;
          children[j] = void 0;
          
          if (j === childrenLen - 1) childrenLen--;
          if (j === min) min++;
          break;
        }
      }


after code change you need to add a new prop of your component "inHTML" 
this prop will help preact to understand that there is a  dangerouslySetInnerHTML in the children

so my component now is:
<Compjsx
myprops={myprops}
inHTML
>
<div>
            <h3 className="popover-title">{popOverTitle}</h3>
            <div className="popover-content" dangerouslySetInnerHTML={{__html: "<div>" + popOverContent + "</div>"}}/>
</div>
</Compjsx>

and now it's working great

Have fun

**Comment by kesha-antonov** [comment]
Please fix this.

**Comment by akaumov** [comment]
I moved render html code in the separate component. It helped me

```js
const DrawHtml = ({html}) => (
	<div
		dangerouslySetInnerHTML={{__html: "<div>" + html + "</div>"}}
	/>
);
```

**Comment by marvinhagemeister** [comment]
I'm unable to reproduce that with Preact X anymore :tada:
