### ISSUE TITLE
No change log for 3.16.0

### ISSUE THREAD

**Issue by sapegin** [developit/preact-compat#374]

**Comment by jt3k** [comment]
These versions differ only in the presence of better compatibility with React.
The isPureReactComponent = true property has been added to the prototype of the PureComponent constructor
```js
PureComponent.prototype.isPureReactComponent = true;
```

**Comment by developit** [comment]
Ah yeah, sorry. That release was done a little more hastily than usual.

**Comment by developit** [comment]
I moved the notes into 3.17.
