### ISSUE TITLE
DraftJS Compatibility - props.children becomes undefined

### ISSUE THREAD

**Issue by nicksrandall** [developit/preact-compat#382]
I'm working on getting draftjs working with preact-compat. In (at least) one component in draft.js, they use a check `this.props.children === ''` to determine if they got an empty text node and then conditionally render based on the result.

See: https://github.com/facebook/draft-js/blob/master/src/component/contents/DraftEditorTextNode.react.js#L88

My issue is that preact-compat converts this.props.children from `['']` to `undefined` here: https://github.com/developit/preact-compat/blob/master/src/index.js#L89

So... the draft.js component doesn't render correctly. 

I'm happy to contribute a fix for this issue but would love to get some feedback first on what is the proper direction to go. 

Also, I can't say thanks enough for this awesome lib!!!

**Comment by nicksrandall** [comment]
Maybe this is related to #366?

**Comment by nicksrandall** [comment]
I'm going to close this issue because even after I solved it, there were many more issues related to draft.js. 

FWIW, I have switched to using ProseMirror and preact and they have been working together beautifully.

**Comment by developit** [comment]
Great, thanks for updating @nicksrandall. ProseMirror is awesome :)
