### ISSUE TITLE
this.base / this.node interoperability

### ISSUE THREAD

**Issue by moimikey** [developit/preact-compat#385]
I can't find documentation or conversation about the significance of `this.base` (which seems to be specific to preact) and its equivalent: `this.node`, part of React's API. If I were to switch from Preact to React, any code that references `this.base` will break. If I were to open up a PR to also return `this.node`, referencing `this.base`, would that cause issue?

**Comment by developit** [comment]
I wasn't aware of `this.node` - is that a replacement for `ReactDOM.findDOMNode(component)`?  Setting up an alias via a getter would be good, PR welcome!
