### ISSUE TITLE
Preact-Compat not working on Babel-register

### ISSUE THREAD

**Issue by abarcenas29** [developit/preact-compat#390]
I am trying to setup an server rending react using react-router-4. While it works just fine on the front-end side (Webpack). It appears that `preact-compat` is not working when used in the server side. I am using `babel-register` so transpile the code.

![image](https://cloud.githubusercontent.com/assets/2470226/26503784/a4e889d0-4274-11e7-8cc0-f3f79b545e80.png)

I have a branch here for reference:
https://github.com/abarcenas29/preact-sandbox-v0/tree/wip/isomorphic-react

to run:
`yarn run install`
`yarn run start:prod`

go to `localhost:3100`

**Comment by developit** [comment]
Babel does not transpile your dependencies in `node_modules`, so using `babel-register` to alias is not a workable way to alias in preact-compat.  You should use a module like [module-alias](https://npm.im/module-alias).  There is a complete explanation of how to use that module here:
https://github.com/developit/preact-compat/issues/299#issuecomment-280499913
