### ISSUE TITLE
Cannot set property createElement of #<Object> which is only a getter. React-hot-loader via preact-compat

### ISSUE THREAD

**Issue by abarcenas29** [developit/preact-compat#392]
I am following this [set of instructions](https://gaearon.github.io/react-hot-loader/getstarted/) on how to setup React hot loarder. But when I go to step 3 where I put the patch, it breaks in to the one below.

![image](https://cloud.githubusercontent.com/assets/2470226/26530172/6ef0e036-4402-11e7-8b51-7b81f40af711.png)

React Hot Loader version: next

Run these commands in the project folder and fill in their results:

1. `node -v`: 7.9.0
2. `npm -v`: 4.2.0

https://github.com/abarcenas29/preact-sandbox-v0/blob/wip/hot-reloader/src/main.js

branch: wip-hot-reloader

Instructions:

* `yarn`
* `yarn run postinstall`
* `yarn run start:dev`

**Comment by developit** [comment]
Hi there - this is an issue with React Hot Loader & ES Modules.  I'm not sure there's a solution yet.

**Comment by ferrybrouwer** [comment]
Add an alias `preact-compat` to the webpack config `resolve.alias` property:

```
resolve: {
    alias:      {
        "react":     "preact-compat",
        "react-dom": "preact-compat",
        "preact-compat": "preact-compat/dist/preact-compat"
    }
}
```

This problem occurs due export es6 modules.

**Comment by morajabi** [comment]
@ferrybrouwer's solution fixes the issue. I think you can close it!

**Comment by developit** [comment]
might be worth us avoiding shipping ES Modules if people are running into this a lot.

**Comment by TomSaporitoXO** [comment]
> might be worth us avoiding shipping ES Modules if people are running into this a lot.

Is this fixed?
