### ISSUE TITLE
Remove `process/browser.js`

### ISSUE THREAD

**Issue by lukeed** [developit/preact-compat#403]
In continuation of #285, I found that `preact-compat` was forcing Webpack to include a `process` shim.

I was able to remove it locally by changing:

```js
var DEV = typeof process==='undefined' || !process.env || process.env.NODE_ENV!=='production';
```

to this:

```js
var DEV = process.env.NODE_ENV!=='production';
```

I can open a PR for this if you don't see a problem with it? Everyone & their mother uses some kind of bundler now, and all bundlers have a `replaceText` or `DefinePlugin` capability. 

For example, with webpack, I did this, the oldest trick in the book:

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development')
}),
```

Before:

<img width="1133" alt="screen shot 2017-07-13 at 6 49 59 pm" src="https://user-images.githubusercontent.com/5855893/28194994-894e39ce-67fc-11e7-8e87-c9d086a73d0a.png">

After: 

<img width="1116" alt="screen shot 2017-07-13 at 6 53 34 pm" src="https://user-images.githubusercontent.com/5855893/28195004-9bdfcbf2-67fc-11e7-937b-18a01941d1f3.png">

---

Worth noting that the `DefinePlugin` trick does not work unless this change is made. This is because instances of `'process'` are found, thus loading the polyfill.

**Comment by lukeed** [comment]
@developit Thoughts? Seems like a simple fix. Also forgot this was still here

I can take care of it but I don't have collab on this repo

**Comment by developit** [comment]
This also affects people using the browser version of preact-compat, where `process` is undefined.

**Comment by kaisermann** [comment]
🤔🤔🤔🤔🤔

What if we inverted the `DEV` conditional to: 

```js 
const DEV = typeof process !== 'undefined' && process.env && process.env.NODE_ENV!=='production'
```

It will fail at `typeof process !== 'undefined'`.

**Comment by kaisermann** [comment]
Or, maybe, even shorter: 

```js
const DEV = typeof process !== 'undefined' && process.env.NODE_ENV!=='production'
```
