### ISSUE TITLE
componentWillUnmount, componentDidmount never fired (resolved)

### ISSUE THREAD

**Issue by simonjoom** [developit/preact-compat#406]
with preact-compat , i ve got a issue that no one Unmount call work:

i succeeded to do it work to add line in :
In newComponentHook(props, context) {
	this.componentWillUnmount = multihook([propsHook, this.componentWillUnmount || 'componentWillUnmount']);
	this.componentDidmount = multihook([propsHook, this.componentDidmount || 'componentDidmount']);

**Comment by developit** [comment]
This is a spelling error: the method name is `componentDidMount()`, not `componentDidmount()` (the `M` is capitalized).

**Comment by simonjoom** [comment]
thanks
