### ISSUE TITLE
Preact Compat works on Server Side but not on Client Side

### ISSUE THREAD

**Issue by csantany** [developit/preact-compat#416]
Hi, I just tried to implement preact-compat using webpack like this:

```javascript
resolve.alias = {
      'react': 'preact-compat',
      'react-dom': 'preact-compat'
};
```

Everything looks good on the server side, but for some reason on the client is not working properly (if you see my gif, you'll see that on the first load you can see the content but after a second removes everything and if I inspect the HTML I got <undefined></undefined>

Any idea?

![](https://media.giphy.com/media/xUNemT0t2AGzmMVsqc/giphy.gif)

Thanks,
Carlos.

**Comment by FallOutChonny** [comment]
Did you solve it?
I have same issue in my SSR project 😢

**Comment by csantany** [comment]
Not yet and looks like this project is not maintained any more, I continue using React.

**Comment by developit** [comment]
This is likely caused by code splitting, which means there'd be no difference when using preact or react.

**Comment by FallOutChonny** [comment]
I think this is caused by module alias incorrect because I've solved it.
your server-side is still using react-dom but client-side use preact-compat

**Comment by developit** [comment]
yup - have also seen that! it'll cause the root element to be rendered differently, which dumps the whole tree and re-renders on the client. While it's not a great symptom, that's actually the correct behavior for Preact (mismatched root shouldn't reuse elements).

**Comment by csantany** [comment]
I tried one more time with my current project, and my results are pretty much the same, works perfect the Server Side Rendering, but the Client Side just give me a blank page.

I'm using React 16.0.0

With SSR:

![screen shot 2017-12-27 at 4 10 33 pm](https://user-images.githubusercontent.com/19692096/34396504-bbeae6aa-eb20-11e7-9e03-a01631adf013.png)

![screen shot 2017-12-27 at 4 10 44 pm](https://user-images.githubusercontent.com/19692096/34396507-c19efa1e-eb20-11e7-8aae-51094d6070d2.png)

With Client Side:

![screen shot 2017-12-27 at 4 10 59 pm](https://user-images.githubusercontent.com/19692096/34396510-cb9225aa-eb20-11e7-822f-e6b531d77806.png)

![screen shot 2017-12-27 at 4 11 07 pm](https://user-images.githubusercontent.com/19692096/34396511-d00f5238-eb20-11e7-91cc-d23f41cc037a.png)

**Comment by csantany** [comment]
@developit why you gave me a 👎 , when I said this project is not maintained or they don't care about issues, is because took 4 months even to receive a response :/

**Comment by csantany** [comment]
@FallOutChonny how exactly did you solved?

**Comment by developit** [comment]
@csantany because it was an unappreciative comment. preact-compat is a community project, not a corporate-sponsored endeavor, and as such it depends on volunteers for maintenance. Many of the volunteers here don't use preact-compat extensively and prefer to only use the preact core ecosystem.
