### ISSUE TITLE
preact-compat React.Children.toArray falsey value handling incompatible with react 

### ISSUE THREAD

**Issue by mrawdon** [developit/preact-compat#419]
The component `<Demo title="Hello, World!" >
		<div/>
		<div/>
		{null}
		{false}
		{undefined}
</Demo>` will have 5 children(counting all falsey values) in preact-compat while only 2 in react.

react
https://codepen.io/anon/pen/xLQWXG
preact-compat
https://codepen.io/anon/pen/wqQmqy

**Comment by marvinhagemeister** [comment]
This is resolved in Preact X :tada: Make sure to alias `preact/compat` instead of `preact-compat`.
