### ISSUE TITLE
Allow installing from github directly by building on "npm install"

### ISSUE THREAD

**Issue by kozak** [developit/preact-compat#424]
Hi, 
I have fixed some minor issues with IE in my own branch (PR here https://github.com/developit/preact-compat/pull/423)

However when trying to use my own version of preact-compat directly from github I run into this issue: https://github.com/npm/npm/issues/3055

Ie: preact-compat requires build artifacts to work when installed via npm install, but they are only included when `prepublish` hook is run. 

If we change this to `prepare` this will also work when installing via `npm install`

**Comment by developit** [comment]
Ah interesting. Any other side effects of changing that script? or is it just an npm 3+ thing

**Comment by kozak** [comment]
To me it seems like this would only affect users like me - trying to do a local install and the package authors. Those scripts aren't run otherwise.  

`npm help scripts` gives the following info: 

```

**Comment by marvinhagemeister** [comment]
Closing. Looks like not enough users have voiced their support for this. If demand is still there, feel free to ping us over at the main [Preact repo](https://github.com/preactjs/preact).
