### ISSUE TITLE
Add `preact-compat/aliases` for consistent use between build tools

### ISSUE THREAD

**Issue by ansballard** [developit/preact-compat#425]
Per https://github.com/developit/preact-compat/pull/398#discussion_r123257215

I was looking into how devtools was split out in the preact repo, and I had a couple questions before diving into a pull request. Currently there's only the single rollup config at the root of the project, but preact has several within a `config/` subdirectory. Would you prefer moving to the subdirectory with both the existing and alias config, or keeping both at the root?

Or, the existing rollup config could export an array of configs, since the new `aliases.js` should be pretty minimal (`module.exports = { /* insert 3-line json here */ };`). Just wanted to see if you had a preference.

**Comment by developit** [comment]
I love this idea. Personally I prefer a single rollup config, but in this case it seems like we could get away with just using ES5 + CommonJS and not even transpiling it?

**Comment by ansballard** [comment]
Yep, I figured that would probably be the simplest option. It shouldn't hurt anything to not export an es6 version, and all the other options involve changing the structure of the project in some way. Unless someone else jumps in before me I'll try to get a pull request in tonight after work!

**Comment by developit** [comment]
Would love a PR if anyone has time! :)

**Comment by ansballard** [comment]
Took a minute to at least figure out what all needs to be included, since I'm lame and never got into this:

- [ ] a straightforward `aliases.js` file in the root that exports all necessary aliases
- [ ] file should not use es6 exports so it doesn't have to be transpiled (`module.exports = { ... }`)
- [ ] docs/working example using webpack (just import in the webpack config and `...` it in the resolve section)
- [ ] docs/working example using browserify (use a separate aliasify config and reference it in package.json like [this](https://github.com/benbria/aliasify#configuration))
- [ ] docs/working example using babel (babel 7 allows for .babelrc.js, which would allow requiring the same as above, but until that is released maybe a hack with local presets like [this?](https://github.com/babel/babel/pull/4892#issuecomment-304537510)
- [ ] docs/working example using brunch (never used it, seems pretty similar to the others since it's a js config file)

**Comment by marvinhagemeister** [comment]
Looks like this has been resolved by using `microbundle` in our main repo :+1:
