### ISSUE TITLE
ReactDOM.findDOMNode does not really work in ref callback

### ISSUE THREAD

**Issue by abrenneke** [developit/preact-compat#429]
My react project uses [react-click-outside](https://github.com/kentor/react-click-outside) for outside click detection. It does a rather idiosyncratic:

```javascript
ref={c => {
  this.__wrappedInstance = c;
  this.__domNode = ReactDOM.findDOMNode(c);
  wrappedRef && wrappedRef(c);
}}
```

Which works in react, but plugging in `preact-compat` causes the component itself to be assigned to `this.__domNode` (because `this.base` is undefined), not the dom node it's expecting, and further down the line it errors.

Not really sure who's at fault here, but I figure if it works in React and not in Preact, something's up.

**Comment by marvinhagemeister** [comment]
This is fixed in Preact 10. Make sure to use `preact/compat` instead of `preact-compat`.
