### ISSUE TITLE
react-css-modules doesn't work: Cannot read property '$$typeof' of undefined

### ISSUE THREAD

**Issue by olegdizus** [developit/preact-compat#43]
Hi! When i trying to work with https://github.com/gajus/react-css-modules in my component webpack compiles it without any errors. But in browser console I receive this error
![image](https://cloud.githubusercontent.com/assets/3694749/14762567/3cdde02e-0986-11e6-8f76-d5df2332cf69.png)

Error appears in this string (blue)
![image](https://cloud.githubusercontent.com/assets/3694749/14762625/a4ad7664-0987-11e6-9c0b-7648085a72b0.png)

My component code looks like this:
![image](https://cloud.githubusercontent.com/assets/3694749/14762581/9237613a-0986-11e6-8fde-0d3ad0d41360.png)

With ES6 class component I receive same error.

Using react-css-modules decorator changes nothing.
Have you any idea how to fix or bypass this error. Thx!

**Comment by developit** [comment]
Just published what I think should be a fix as `preact-compat@1.7.1`. Let me know if it works! :)

**Comment by olegdizus** [comment]
WOW! This works great! Thanks a lot!

P. S. maybe react-css-modules does not have sense to use with preact -- it's adds 45 kb extra size to bundle. It's just a classname helper! =)) Anyway, thx!

**Comment by developit** [comment]
I didn't want to suggest it, but that was my immediate thought as well.  My typical approach is to use CSS Modules via Webpack's `css-loader`.  It means writing a little more verbose code, but there is no runtime dependency:

```js
import styles from './styles.scss';

const App = () => (
  <div class={styles.app}>Tastyprojects</div>
);
```

Cheers!
