### ISSUE TITLE
Will Preact stay API compatible with React 16?

### ISSUE THREAD

**Issue by drcmda** [developit/preact-compat#432]
We usually alias to Preact in production because of the payload savings, but now that we moved to React 16 which was officially released yesterday, preact-compat is down (for instance when returning arrays). That raises questions as to how far we can go with Fiber anyway, even if preact-compat can patch some minor things. But will it support returning arrays, numbers and strings as results, portals, and eventually async scheduling?  

![screen shot 2017-09-27 at 12 32 03](https://user-images.githubusercontent.com/2223602/30909055-06b5f546-a380-11e7-9683-1ebc7240a8d6.png)

**Comment by developit** [comment]
Hi there! All good questions. Preact-compat has to account for all of these changes, but some of them will remain in compat and not in core. Here's a list:

- Returning Arrays from render(): yes, but this is a huge change for Preact itself. It will come, but it will take time.
- Numbers & strings: this has always been supported in Preact.
- Portals: I like the idea, but there are things like event bubbling redirection that might be unworkable within preact. We'll probably have to patch them into compat.
- Async scheduling: this will absolutely be coming to Preact itself, and we'll ship a decent scheduler enabled by-default in preact-compat once it's available.

**Comment by HillLiu** [comment]
And hydrate

https://reactjs.org/docs/react-dom.html#hydrate

**Comment by vorillaz** [comment]
Waiting for hydrate since this is a breaking change for aliasing with Next.js

**Comment by effulgentsia** [comment]
> Returning Arrays from render(): yes, but this is a huge change for Preact itself. It will come, but it will take time.

Is there an issue to follow for that? [#406](https://github.com/developit/preact/issues/406) is closed. I don't know if it's appropriate to reopen that one or start with a new one: is there definitely agreement that it's for Preact rather than for Preact-compat?

**Comment by developit** [comment]
@effulgentsia I think most people want Array returns in preact itself, but it's also quite possible doing so would necessitate a rewrite of the diff. In terms of ongoing discussion, @tkh44 was working some magic in #703.

**Comment by vorillaz** [comment]
@developit Watching this closely as Next.js is strictly packed with React 16. Is there any chance to help you out with missing API changes?

**Comment by acao** [comment]
`ReactDom.hydrate()` will be tricky - `ReactDom` got quite the overhaul in React 16.

**Comment by developit** [comment]
Yes! Jump on [slack](https://preact-slack.now.sh) and we can work out what to do.

**Comment by alexparish** [comment]
Does anyone have a rough timeline for React 16 compatibility? Particularly interested in support for the `hydrate` function.

**Comment by marvinhagemeister** [comment]
Note, we added all of those in Preact X :tada: We even ship with a rough implementation fo `Suspense` but that is not ready for production yet :tada:
