### ISSUE TITLE
The main fiddle is throwing an error about PropTypes

### ISSUE THREAD

**Issue by SheetJSDev** [developit/preact-compat#435]
https://jsfiddle.net/developit/61cqu193/

Console shows: `Uncaught TypeError: PropTypes.checkPropTypes is not a function` (and HTML pane shows some JS code)

Removing the propTypes appears to work: 

<details><summary>Fiddle code (click to show)</summary>

```js
let ReactDOM = preactCompat,
	React = preactCompat;

class Foo extends React.Component {
	render() {
		let { theme, bar, children } = this.props;
		return <h2 style={theme} bar={bar}>{ children }</h2>;
	}
}

ReactDOM.render((
	<div>
		<Foo bar={true} theme={{ color:'green' }}>Demo</Foo>
	</div>
), document.body);
```

</details>

Since this demo is intended to show the use of `preact-compat`, I would recommend using a simpler example without PropTypes for this library and making a new PropTypes-powered fiddle for the `proptypes` library.

**Comment by dandv** [comment]
Getting the same error and this strange output:

![image](https://user-images.githubusercontent.com/33569/36932359-9f24f6e8-1e7c-11e8-966b-73c4092bfb44.png)

**Comment by developit** [comment]
Fixed. Was using the old (wrong) proptypes package.
