### ISSUE TITLE
Loading Rule Error  'compat/compat':rule.create

### ISSUE THREAD

**Issue by Ketcap** [developit/preact-compat#437]
I just created preact app via cli and opened on vscode. The errors pops up instantly i open any js files. 

Error : Error while loading rule 'compat/compat': rule.create is not a function

Eslint is global and the version is v3.19.0
Preact Cli just installed version is 1.4.1

![screen shot 2017-10-05 at 1 34 58 pm](https://user-images.githubusercontent.com/7689820/31223254-6181696c-a9d2-11e7-8c59-13784683104e.png)

**Comment by Ketcap** [comment]
Thought it could be eslint version. 

Updated v4.8.0 still same error.

**Comment by pl12133** [comment]
This looks a lot like https://github.com/amilajack/eslint-plugin-compat/issues/96.

**Comment by Ketcap** [comment]
thank you i keep eye on that :)
