### ISSUE TITLE
ERROR in ./~/react-dom/lib/ReactMount.js

### ISSUE THREAD

**Issue by Karthikmuthupandi** [developit/preact-compat#441]
Hi All,
I am getting the below while doing web pack operation. I am try to migrate react to preact. Kindly do some suggestion or help.

ERROR in ./~/react-dom/lib/ReactMount.js
    Module not found: Error: Can't resolve 'react/lib/React'

Thanks
Karthi

**Comment by developit** [comment]
Use `"React$"` as the key in your webpack alias setup.

**Comment by marvinhagemeister** [comment]
Note, we've removed support for deprecated APIs in compat with Preact X
