### ISSUE TITLE
this.setState not work in Mixins.

### ISSUE THREAD

**Issue by jchbh-duplicate** [developit/preact-compat#442]
Use react-data-grid to build a grid, using preact-compat + preact-cli but received:

Uncaught (in promise) TypeError: this.setState is not a function     
at Object.updateScroll (react-data-grid.js?57d0:13603)     
at Object.metricsUpdated (react-data-grid.js?57d0:13603)     
at Object.updateMetrics (react-data-grid.js?57d0:5664)     
at Object.componentDidMount (react-data-grid.js?57d0:5664)     
at Object.chainedFunction [as componentDidMount] (react-data-grid.js?57d0:9915)     
at flushMounts (preact.js?10a9:103)     at renderComponent (preact.js?10a9:318)     
at rerender (preact.js?10a9:38)     at <anonymous>

console log `this` on updateScroll when exception, 
It seems there is not `this.setState`, but `this.state` exists.

check `__proto__` too 

I think maybe there is some problem to applyMixins to copy methods into react object?

**Package Version:**
preact: 8.2.6
preact-cli: 1.4.1
preact-compat: 3.17.0
react-data-grid: 2.0.73

**preact.config.js**
```
export default function (config, env, helpers) {
  /** you can change config here * */
  config.plugins = config.plugins.filter(v => (v.constructor.name !== 'UglifyJsPlugin'));
  console.log(config.resolve);
}
```
```
alias:
   { 'preact-cli-entrypoint': ...,
     style: ...,
     'preact$': ...,
     react: 'preact-compat',
     'react-dom': 'preact-compat',
     'create-react-class': 'preact-compat/lib/create-react-class',
     'react-addons-css-transition-group': 'preact-css-transition-group',
     'preact-cli/async-component': ... } }
```

`alias` seems already contain `create-react-class`.

**Comment by christian-fei** [comment]
Hello @jchbh-duplicate ,
i am having the same issue.
Did you find any solution?

**Comment by AlexKvazos** [comment]
Also having this issue. Any solutions to mixins?

**Comment by developit** [comment]
Is anyone still using mixins?

**Comment by marvinhagemeister** [comment]
With Preact X we removed support for mixins. They've been long deprecated (even in React). Please switch to ES6 classes, plain functions, or hooks to share code across components.
