### ISSUE TITLE
React.createFactory error when prototype of config is null.

### ISSUE THREAD

**Issue by jo32** [developit/preact-compat#443]
see
preact-compat: https://jsfiddle.net/jo32/y3fb3mfe/
vs
react: https://jsfiddle.net/jo32/gxvm5agy/

**Comment by developit** [comment]
If anyone wants to PR, the solution here is either to avoid `hasOwnProperty()` when cloning (reasonable), or use an aliased `hasOwnProperty.call(o)` (not great).

**Comment by marvinhagemeister** [comment]
FYI: We removed the factory API completely in `preact/compat`. It has been marked as deprecated for years now, so we decided to drop it.
