### ISSUE TITLE
Element.getAttribute return null

### ISSUE THREAD

**Issue by jo32** [developit/preact-compat#446]
React: https://jsfiddle.net/jo32/L08z97ky/

vs

preact-compat: https://jsfiddle.net/jo32/bp8qye64/

**Comment by developit** [comment]
I don't think we'll be fixing this, it's likely to change in upcoming React releases. JavaScript accessing the DOM should prefer reflected properties over attributes.

**Comment by developit** [comment]
Closing as wontfix. Exposing input values as attributes is an attack vector and not something we should be doing. It might be different from React's behavior (though I believe they've stopped since there was a CSS input logging demo at some point), but it's the correct thing to do.
