### ISSUE TITLE
ref is lost when creating element by React.createFactory

### ISSUE THREAD

**Issue by jo32** [developit/preact-compat#447]
React: https://jsfiddle.net/jo32/2srauotc/

vs

preact-compat: https://jsfiddle.net/jo32/8whrnq6w/

**Comment by developit** [comment]
hmm - it's not stored as a property of the element, but a prop:
https://jsfiddle.net/developit/8whrnq6w/1/

**Comment by developit** [comment]
Marking this as `discussion` - there are lots of properties persisted on JSX elements in React that don't really warrant being replicated in preact-compat, since they're undocumented internals.
