### ISSUE TITLE
defaultValue is not set

### ISSUE THREAD

**Issue by jo32** [developit/preact-compat#449]
```
var container = document.createElement('div');
ReactDOM.render(<textarea defaultValue="foo" />, container);

console.log(container.firstChild.defaultValue); // should be "foo" but got ""
```

https://jsfiddle.net/jo32/eremfzgy/

**Comment by developit** [comment]
Thanks, we should be able to patch this into -compat.

**Comment by developit** [comment]
This [appears to be fixed](https://jsfiddle.net/eremfzgy/2/). `defaultValue` is set as `value` on first render, as it is in React.
