### ISSUE TITLE
Implement something like error boundaries

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [developit/preact-compat#453]
https://reactjs.org/docs/error-boundaries.html

**Comment by developit** [comment]
On the radar, but this is much more likely to be implemented in Preact itself:
developit/preact#886

**Comment by reznord** [comment]
You can track the active development of the issue here: https://github.com/developit/preact/pull/819

**Comment by developit** [comment]
Closing since we're working on it in the other repo.
