### ISSUE TITLE
Issues when rendering rows on react-table

### ISSUE THREAD

**Issue by ugin** [developit/preact-compat#460]
Original example that works: https://codesandbox.io/s/wjrn8wy3R

Exact example using preact-compat: https://codesandbox.io/s/n3o9j013rj
Switch the rows count from 10 to 5 and back to 10.

I've checked the react-table source (adding logs) and the children count passed to the TbodyComponent are correct, but when rendered somehow it adds the old children from the virtual-dom, hope it helps.

**Comment by Ehernandez0921** [comment]
It looks like they are resolving it in the react-table library. @rantecki has made the change. I don't know how to reference from another repository.

(https://github.com/react-tools/react-table/issues/827)

**Comment by ugin** [comment]
So it's not related to preact, rantecki caught the error source. Thanks for feedback.
