### ISSUE TITLE
TypeError: Cannot call a class as a function when using with React Component

### ISSUE THREAD

**Issue by rafaelklaessen** [developit/preact-compat#467]
Hi!
I'm trying to use [react-tradingview-widget](https://github.com/rafaelklaessen/react-tradingview-widget) with a Preact project and I'm getting the following error:
![screen shot 2018-03-03 at 15 15 41](https://user-images.githubusercontent.com/15846964/36935247-c5ab6512-1ef5-11e8-8f89-49abe4de72cf.png)

I'm not experienced with Preact or Preact Compat so I've got no idea what causes this error. Other React components seem to work fine.

The Preact project was created with `preact create material [name]` and I'm using the following code to render the component:
```javascript
<TradingViewWidget symbol="NASDAQ:AAPL" />
```

**Comment by developit** [comment]
@rafaelklaessen don't use an arrow function for [your render method](https://github.com/rafaelklaessen/react-tradingview-widget/blob/master/src/index.js#L202). It's wasteful (a new function is created for every instance of the class), and Preact might end up thinking your classful component is a function.
