### ISSUE TITLE
Missing createRef

### ISSUE THREAD

**Issue by Pyrolistical** [developit/preact-compat#474]
Is createRef planning to be added?

**Comment by k1r0s** [comment]
Thanks @Pyrolistical 

We just create a PR over this subject
https://github.com/developit/preact/pull/1138

**Comment by johnhaitas** [comment]
any projection on when this addition will be released?

**Comment by k1r0s** [comment]
soon :)

**Comment by shermango** [comment]
any update on this addition? If I recall correctly it was dependent on `Preact 8.4.x` release which was a while ago?

**Comment by yonatanmn** [comment]
Seems like it's merged in "master", but not published. Any update ?

**Comment by Nicolab** [comment]
Please, an update?

**Comment by marvinhagemeister** [comment]
@Nicolab It's already out in our next major version for Preact that's currently in alpha stat. Compat has moved into core and can be imported via `preact/compat` instead 👍🎉

**Comment by Nicolab** [comment]
Ok, thanks :+1:
