### ISSUE TITLE
Material-UI 1.2.1 not working with Preact

### ISSUE THREAD

**Issue by vinaybedre** [developit/preact-compat#476]
Hi,

Just create a default template preact-cli project, add material-ui and just use Button at https://material-ui.com/getting-started/usage/

An error is thrown: Material-UI: react@16.3.0 or greater is required

Error comes from the file https://github.com/mui-org/material-ui/blob/3353f440053222b4eed36f575593b5bfcfa7a0f3/packages/material-ui/src/ButtonBase/ButtonBase.js and line 48.

How can we make React.createContext?

Can you please help?

**Comment by developit** [comment]
Use an older version of material-UI for now. Adding fake API's to preact-compat isn't going to solve this issue for you, we need fundamental changes like fragments before we have proper React 16 compatibility.

**Comment by oliviertassinari** [comment]
We do the following in in order to check the support for `getDerivedStateFromProps()`.
```jsx
if (process.env.NODE_ENV !== 'production' && !React.createContext) {
  throw new Error('Material-UI: react@16.3.0 or greater is required.');
}
```

We can improve the detection logic if Preact support this hook.

**Comment by benwiley4000** [comment]
@developit is there an issue tracking the development of React.Fragment?

**Comment by Kanaye** [comment]
Yes there is developit/preact#946, developit/preact#1047 and a wip PR for fragements developit/preact#1080

**Comment by developit** [comment]
We just shipped `getDerivedStateFromProps()` in [Preact 8.3.0](https://github.com/developit/preact/releases/tag/8.3.0). `createContext()` likely won't be coming to Preact core, we will need to integrate something like preact-context into compat (see #475).

**Comment by oliviertassinari** [comment]
@developit It's good to know! We the Fragment and Portal API, we should be able to make Material-UI work with Preact.

**Comment by coder82** [comment]
is there a workaround for this at the moment?

**Comment by oliviertassinari** [comment]
@coder82 We are planning on using the new context API of React. Things won't get any better.

**Comment by sriharrsha** [comment]
@oliviertassinari  So what do say...will we not able to make preact-compat or inferno-compat work with Material-UI?

**Comment by oliviertassinari** [comment]
@sriharrsha It's going to be a large effort. This will be even more true after the hook migration.

**Comment by sriharrsha** [comment]
Yeah, Is there any other alternative UI Lib you would recommend for Preact

**Comment by oliviertassinari** [comment]
@sriharrsha I have never used Preact, I can't help with that.

**Comment by marvinhagemeister** [comment]
Just an FYI: That we will add hooks in a point release when they are marked as stable. Preact X adds `Fragments` so there's one less thing to be worried about.

**Comment by oliviertassinari** [comment]
@marvinhagemeister Great for the `Fragment` support 👍. I guess we only miss `createContext()` then.

**Comment by mnunes01** [comment]
Whats the current status on this? since preact X inplemented most features of hooks, are we able to use material ui with preactX?

**Comment by marvinhagemeister** [comment]
@mnues01 you should be able to use it just fine with Preact X. We're not aware of any issues with it and iirc some people in our slack channel are using it.

Just make sure to alias to `preact/compat` instead of the library in this repo.

Closing, because it's unlikely that we'll backport everything to 8.x.

**Comment by oliviertassinari** [comment]
Also, I would rather start with Material-UI v4 that was 100% rewritten with hooks than v1. v1 might still rely on some legacy lifecycles and private context API, I'm not sure Preact v10 supports it. Starting with v4 is much safer. You can find an example: https://github.com/mui-org/material-ui/tree/master/examples/preact

**Comment by mnunes01** [comment]
yes i am using v4 and preact/compat it compiles, but i am having some issue with modal on <Dialog> component.
any idea?
![Screenshot 2019-07-18 at 13 54 28](https://user-images.githubusercontent.com/6908949/61455383-a238d200-a963-11e9-8772-20ddc8ec9430.png)

**Comment by oliviertassinari** [comment]
@mnunes01 Hum, it sounds like an issue with the ref triggers order. We might change ref the logic a bit in https://github.com/mui-org/material-ui/pull/16597. Could you try again when it land? Alternatively, if you want to dive into the problem, feel free to.

**Comment by mnunes01** [comment]
@oliviertassinari i guess it is indeed, going a bit deeper on it, it seems some async issue.
if i do pause the debugger just before the if(!containerInfo.restore) the debugger shows containerInfo as undefined, but by the time it throws the error execption containerInfo is and object with the correct values.

![Screenshot 2019-07-18 at 14 21 01](https://user-images.githubusercontent.com/6908949/61457287-46bd1300-a968-11e9-8a0c-ded278f68076.png)
