### ISSUE TITLE
setState raised error

### ISSUE THREAD

**Issue by engmagdy87** [developit/preact-compat#481]
After build the React 16 app with preact-compat, I received this error when calling a function with setState for onClick event

![42091208-b793cbd4-7ba4-11e8-9e99-98c7e9f17a84](https://user-images.githubusercontent.com/8473421/42094564-75895c70-7bb0-11e8-8e7f-33e6048b939c.PNG)

**Comment by developit** [comment]
We only shipped `createPortal()` in 3.18.2 (3 days ago). Please update.
