### ISSUE TITLE
react-swipeable-views: We are expecting a valid React Element

### ISSUE THREAD

**Issue by jpodwys** [developit/preact-compat#487]
While trying to use `react-swipeable-views` with `peact` via `preact-compat`, `react-swipeable-views` floods my console with `We are expecting a valid React Element` errors.

`react-swipeable-views` [is using](https://github.com/oliviertassinari/react-swipeable-views/blob/f73e51aa0c8463c4c77eae7e2ea5fe10c429b462/packages/react-swipeable-views/src/SwipeableViews.js#L811-L815) `React.isValidElement(child)`. It seems this call returns `false` when passed a `preact` node despite the fact that I'm using `preact-compat`.

Is this a case `preact-compat` attempts to solve? Have I don't something wrong? Should I report this issue elsewhere?

Thank you!

**Comment by jpodwys** [comment]
@developit do you have any insight into this?

**Comment by developit** [comment]
This is very likely the same root cause as #484 (UglifyJS bug).

**Comment by jpodwys** [comment]
Thanks for the response! I'll give the suggestion in that issue a try. If it works out then I'll close this issue and watch that one.

**Comment by developit** [comment]
Just an update - we released [Preact 8.3.0](https://github.com/developit/preact/releases/tag/8.3.0), which should fix this issue.

**Comment by jpodwys** [comment]
Thank you, I should get the update automatically. I'll try removing the other solution.
