### ISSUE TITLE
Reverse compatibility layer

### ISSUE THREAD

**Issue by edygarOliveira** [developit/preact-compat#489]
Is there any layer to consume preact-specific components in React? I mean, some module which would polyfill the `h` to `createElement`, `render` and so on?

**Comment by developit** [comment]
**react-compat.js**:

```js
import { createElement, cloneElement, render, findDOMNode, Component as ReactComponent } from 'react';

function h() {
  const vnode = createElement.apply(this, arguments);
  vnode.attributes = vnode.props;
  vnode.nodeName = vnode.tag;
  return vnode;
}

class Component extends ReactComponent {
  get base() {
    return findDOMNode(this);
  }
}

export default { render, h, createElement: h, cloneElement, Component };
export { render, h, h as createElement, cloneElement, Component };
```

**Comment by Ivy4** [comment]
@developit where would this go in the build process?

**Comment by hadim** [comment]
Could you give a more complete example? I am having trouble to make it work.

My React project is setup `react-scripts`, I have added your script and added:

```
"module": {
    "exports": {
      "settings": {
        "import/resolver": {
          "alias": {
            "preact:": "./src/react-compat.js"
          }
        }
      }
    }
  }
```

to the `.eslintrc` file and also added the module `eslint-import-resolver-alias`.

I am not sure that setup is correct and I have an error trying to render the preact component:

```
Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Comment by hadim** [comment]
(note that the project uses React 16.5)
