### ISSUE TITLE
findDOMNode is different from react-dom

### ISSUE THREAD

**Issue by zhaopeifei** [developit/preact-compat#493]
`function findDOMNode() { 
    return e && e.base || null
}`

but in react-dom
`function findDOMNode(componentOrElement) {
  // ...
  if (componentOrElement == null) {
    return null;
  }
  if (componentOrElement.nodeType === 1) {
    return componentOrElement;
  }
  // ...
`

so when I use findDOMNode(element)，react-dom return element，but preact return null. This cause react-slick make a mistake.

**Comment by billneff79** [comment]
We are encountering the same issues with `react-slick`.  I created a fix for this issue in PR #495

**Comment by rdmurphy** [comment]
Can confirm this is triggering errors in [`react-autocomplete`](https://github.com/reactjs/react-autocomplete) too.

**Comment by dandv** [comment]
@mlaursen suspects that `findDOMNode` may also cause the [incompatibility with react-md](https://github.com/mlaursen/react-md/issues/788). I've made sure preact-compat is at 3.18.4 in my reproduction repo (linked above), but I still see the issue.
