### ISSUE TITLE
Transform React children to Preact children

### ISSUE THREAD

**Issue by Bunlong** [developit/preact-compat#503]
Hi @developit,  How could I transform React children format to Preact children format?

```
/** @jsx h */
import Preact, { h } from "preact"
import React from 'react'

class PreactWidget extends React.Component {
  constructor() {
    super()
    this.divRef = React.createRef()
  }
  
  componentDidMount() {
    this.renderPreact()
  }

  componentDidUpdate() {
    this.renderPreact()
  }

  renderPreact() {
    const children = this.props.children

    Preact.render(
      children,
      this.divRef.current
    )
  }

  render() {
    let h = React.createElement
    return <div ref={this.divRef} />
  }
}

export default PreactWidget
```

```
class PreactComponent extends Preact.Component {
  render() {
    return <div>Hello World!</div>;
  }
}

class Benchmarks extends React.Component {
  render() {
    return(
      <PreactWidget>
        <PreactComponent />
      </PreactWidget>
    )
  }
}
```

**Comment by Bunlong** [comment]
Hi @developit Could you pls help to solve this issues for this project [(preact-widget)](https://github.com/themodernjavascript/preact-widget)? Thanks!

**Comment by marvinhagemeister** [comment]
It's hard to tell without more information like the error message you are getting. Guessing from your second code snippet it seems like you are mixing jsx factory functions from `react` and `preact`.

The easiest approach with least effort would be to use [preact-compat](https://github.com/developit/preact-compat) and aliasing it to `react` imports.

If you do not want to do this you'll have to put in quite a bit of work (it's doable though).

Basically you'd have to recursively convert the result of `React.createElement(PreactComponent, null)` (which will be the vnode structure of react), into preact's vnode structure. Inside the react codebase this is commonly referred to as [ReactElement](https://github.com/facebook/react/blob/a3e4d00089571b66c151b9ac1bd9c589d03b2f27/packages/react/src/ReactElement.js#L111). This should be doable with a simple depth-first-search traversal.

The most obvious differences between react's and our vnode are these:

| React | Preact |
|---|---|
| `vnode.type` | `vnode.nodeName` |
| `vnode.props` | `vnode.attributes` |
| `vnode.props.children` | `vnode.children` (must always be an array) |

As mentioned the [preact-compat](https://github.com/developit/preact-compat) codebase is a great reference for how the conversion is done.
