### ISSUE TITLE
preact-compat Children.only differs from Reacts Children.only

### ISSUE THREAD

**Issue by Hotell** [developit/preact-compat#506]
React's Children.only uses `isValidElement` under the hood. I guess we should same errors like within react.

Use case:

you component should be restricted to have one children and it should be a function ( render prop pattern via children )

This is valid within preact+preact-compat

```js
class Test extends Component {
  render() {
    const children = Children.only(this.props.children);

    if (typeof children !== 'function') {
      throw new Error('we need 1 function human!');
    }

    return children();
  }
}
```

in react it will on `Children.only(this.props.children)` when child's gonna be a function, because of mentioned `isValidElement`:

https://github.com/facebook/react/blob/master/packages/react/src/ReactChildren.js#L389

```js
class Test extends Component {
  render() {
    // error
    const children = Children.only(this.props.children);

    if (typeof children !== 'function') {
      throw new Error('we need 1 function human!');
    }

    return children();
  }
}
```

```jsx
const App = () => <Test>{() => <div>just testing</div>}</Test>;
```

**Comment by marvinhagemeister** [comment]
This is resolved in Preact X. Make sure to alias `preact/compat` instead of `preact-compat`.
