### ISSUE TITLE
Should babel module loader work for react / reactish dependencies inside node_modules?

### ISSUE THREAD

**Issue by nineohnine** [developit/preact-compat#513]
I am trying to build a ssr & client side app using preact.  I am using babel-node with your module-loader configuration.  I am getting errors from inside my dependency that it cannot load resolve react.  Is this to be expected ?  I can resolve react (preact-compat) from my project files.   But when a dependency of my project does it throws.   Is this the expected behavior or am i doing something wrong?

Thanks!

**Comment by marvinhagemeister** [comment]
> I am using babel-node with your module-loader configuration

Can you elaborate on your setup? In general mixin `preact` with `react` only works by rewriting (aka aliasing) imports. If you're using `babel-node` alone you'll likely need to add a plugin that switches out imports to `react`.

**Comment by nineohnine** [comment]
yep so I am using this setup in my babelrc from the readme:

```
{
    // ...
    "plugins": [
        ["module-resolver", {
        "root": ["."],
        "alias": {
            "react": "preact-compat",
            "react-dom": "preact-compat",
            // Not necessary unless you consume a module using `createClass`
            "create-react-class": "preact-compat/lib/create-react-class",
            // Not necessary unless you consume a module requiring `react-dom-factories`
            "react-dom-factories": "preact-compat/lib/react-dom-factories"
        }
        }]
    ],
    "presets": [
        "react"
    ]
    // ...
}
```

**Comment by developit** [comment]
If you're not running Babel on node_modules (most people don't), the aliases set in your Babel config are not applied to those files. 

You should use `module-alias` instead, which applies to all requires:

https://github.com/developit/preact-compat/issues/299#issuecomment-280499913
