### ISSUE TITLE
I got an error: 'h' must be in scope when using JSX

### ISSUE THREAD

**Issue by rafi16jan** [developit/preact-compat#514]
I got an error: 'h' must be in scope when using JSX

I'm manually tweaking react dependencies from a react template and got this. What should I do?

**Comment by rafi16jan** [comment]
Sorry wrong repo. I should report this to just-boris/create-preact-app because I use his dependencies.

**Comment by marvinhagemeister** [comment]
@rafi16jan Most likely the import for `h` is missing. Check that there is an import for `h` present:

```js
import { h } from 'preact';
```
