### ISSUE TITLE
When I use inline-react-svg, it occur error `Uncaught TypeError: Cannot convert a Symbol value to a string` 

### ISSUE THREAD

**Issue by ohute-couture** [developit/preact-compat#519]
Hi, 

I want to use [babel-plugin-inline-react-svg](https://github.com/airbnb/babel-plugin-inline-react-svg)
But, preact-compat occur error 
It is same when I use [parcel-plugin-svgr](https://github.com/smooth-code/svgr/tree/master/packages/parcel-plugin-svgr)

```
props.js:60 Uncaught TypeError: Cannot convert a Symbol value to a string
    at w (props.js:60)
    at g (props.js:15)
    at A (index.js:260)
    at _ (index.js:154)
    at _ (index.js:140)
    at d (children.js:74)
    at A (index.js:263)
    at _ (index.js:154)
    at d (children.js:74)
    at _ (index.js:44)
```

![image](https://user-images.githubusercontent.com/25993421/54193976-81b4c300-44fe-11e9-8cbe-7eef82da0968.png)

I am using preact, TS, parcel 
I think, props `undefined` makes error 
fix this please ..

**Comment by marvinhagemeister** [comment]
Do you have a repository or codesandbox where we can reproduce the issue you are experiencing? This helps us tremendously in fixing bugs👍

**Comment by ohute-couture** [comment]
You can check the code https://github.com/ohute-couture/preact_code_sand_box
and check `console.error` https://ohute-couture.github.io/preact_code_sand_box/ (open dev tool)

when I made code sand box, I found it makes error next element have a style property 
[check this](https://github.com/ohute-couture/preact_code_sand_box/blob/master/src/index.jsx#L11)

**Comment by marvinhagemeister** [comment]
@ohute-couture The issues you're seeing are caused by mixing Preact X with `preact-compat` for Preact 8.x.

To fix this issue:

1. Uninstall `preact-compat` via `npm uninstall preact-compat
2. Change the aliasing in `package.json` to use the `preact/compat` import from Preact X:

```json
"alias": {
  "react": "preact/compat",
  "react-dom": "preact/compat"
},
```

**Comment by ohute-couture** [comment]
Thank you very much!! 👏👏👏👏👏
