### ISSUE TITLE
Uncaught ReferenceError: preact is not defined

### ISSUE THREAD

**Issue by didymu5** [developit/preact-compat#520]
Hello I could use some help. I'm using preact X -alpha 2 and getting the following error
```
index.js:32 Uncaught ReferenceError: preact is not defined
    at Module../src/index.js (index.js:32)
    at __webpack_require__ (bootstrap:63)
    at Object.2 (preact-app.bundle.js:20420)
    at __webpack_require__ (bootstrap:63)
    at bootstrap:195
    at bootstrap:195
```

index.js
```
import {h, render} from 'preact';
const App = () => {
  return (
    <div>
Hello app
    </div>
  );
};
render(<App />, document.getElementById("my-preact-app"));
```

package.json
```
"dependencies": {
"preact": "^10.0.0-alpha.2"
}
```
.babelrc
```
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": ["last 2 versions", "safari >= 7"]
        }
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "preact.h"
      }
    ],
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by didymu5** [comment]
The error is labeled when the render() is called.

**Comment by didymu5** [comment]
I could console log 
```
console.log(h, render)
```
and can see that there are functions returned, however
console.log `preact` gives me undefined.

**Comment by lukeed** [comment]
I _think_ your babel `pragma` needs to just be `'h'`, not `'preact.h'`

**Comment by didymu5** [comment]
OOH that did it!!!

**Comment by lukeed** [comment]
Nice! 

Yeah, makes sense. You're no longer keeping `preact` in the global namespace though.

Also verified that `preact-cli` is [correctly configured](https://github.com/developit/preact-cli/blob/next/packages/cli/lib/lib/babel-config.js#L34) for this 👍 

Closing, but please follow up if there are any other issues~!
