### ISSUE TITLE
Is there any way to use preact in Docz?

### ISSUE THREAD

**Issue by evont** [developit/preact-compat#525]
I want to use docz to write the components documents, but when I set react alias as preact-compat, it warns me that "export 'useState' was not found in 'react'", is there any way to use preact in Docz?

**Comment by marvinhagemeister** [comment]
Hooks are available in our next major version for Preact. The [release notes](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0) have a section on how to upgrade. Note that compat has moved to core. If you run into an issue please report it over at our main repo 🙂
