### ISSUE TITLE
preact-compat crashes when trying to migrate react functions + hooks to preact

### ISSUE THREAD

**Issue by vtcaregorodtcev** [developit/preact-compat#536]
Have application written in react using only `react functions and hooks` somewhere (`useState`, `useEffect` only). Follow preact migration where I see, `"I need to add only two lines"` aliases for react and react-dom in my webpack config.

after those manipulations I get error: 
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (preact-compat.es.js:80)
    at Module../node_modules/preact-compat/dist/preact-compat.es.js (main.js:11604)
    at __webpack_require__ (main.js:727)
    at fn (main.js:101)
    at eval (index.jsx:2)
    at Module../src/index.jsx (main.js:16111)
    at __webpack_require__ (main.js:727)
    at fn (main.js:101)
    at eval (webpack:///multi_(:8080/webpack)-dev-server/client?:3:18)
    at Object.0 (main.js:16194)
```

error at `VNode.prototype.$$typeof = REACT_ELEMENT_TYPE;`

trying to migrate this project `https://github.com/vtcaregorodtcev/fuckts-maps/tree/use-preact`

can someone help me with that? where I should dig? 
is it trouble with `preact-compat` or with `antd` or `react-draggable` which I use in it? 

<img width="948" alt="Снимок экрана 2019-11-18 в 23 03 27" src="https://user-images.githubusercontent.com/24553355/69087164-abdc5e80-0a57-11ea-8705-53fbe6247aa7.png">

**Comment by Kanaye** [comment]
It looks like you are using preact@10 with `preact-compat`. 
Compat has been integrated into the preact main package.
Change your alias from `preact-compat` to pont to `preact/compat` and uninstall `preact-compat` just to be sure.
If you encounter other issues after that change please report them at the main preact repo.

**Comment by marvinhagemeister** [comment]
@Kanaye summed it up perfectly :+1: You need to switch to `preact/compat` for Preact 10 :+1:

**Comment by emilastanov** [comment]
Awesome
