### ISSUE TITLE
Add support for `this.forceUpdate()`

### ISSUE THREAD

**Issue by fdaciuk** [developit/preact-compat#7]
ReactJS has a function `forceUpdate()`, to use with 3rd-party modules, that need update a component without changing the React state.

`preact` does not have this function. When we need to force an update, we've got an error :(

--- 

PS.: Using `this.setState({})` instead `this.forceUpdate()` works fine on React and Preact :smile: Thanks @developit for the tip! =)

**Comment by developit** [comment]
Good catch, I'll get this added today.

**Comment by developit** [comment]
`forceUpdate()` has been added to Preact in `3.3.0`.

**Comment by fdaciuk** [comment]
:+1: :sparkles: :sparkles:
