### ISSUE TITLE
React#cloneElement does not clone vnode children

### ISSUE THREAD

**Issue by zenfe** [developit/preact-compat#72]
`React#cloneElement` does not clone vnode `children` because they are stored externally from the `attributes `property.

Since reactjs stores the `children `on `props`, they get cloned. Only if extra `children` are provided to the `React#cloneElement `call do they get overridden.

**Comment by developit** [comment]
Looks like a bug. This is actually fixed in preact 5.0, but the change won't make effect until preact-compat removes its implementation.

**Comment by developit** [comment]
@zenfe Please let me know if `preact-compat@1.8.0` fixes the issue for you!

**Comment by guywald1** [comment]
Also experiencing this issue :(

P.S. Adore Preact!

**Comment by developit** [comment]
@guywald1 this was fixed 8 months ago. Are you sure you're seeing the same thing? Repro would be good.

**Comment by guywald1** [comment]
Thanks for maybe being vague. Perhaps I am misinterpreting the issue, but using React, this:

```jsx
// SomeRandomComponent.jsx
// ... inside .render()
{ React.Children.map(this.props.children,
  child => this.state.isMenuClosed ? null : React.cloneElement(child, { customProp: 'foo' })) }
```

will not work properly when aliasing React and ReactDOM as `preact-compat` in `webpack`. Meaning, the children will not be rendered at all.

**Comment by developit** [comment]
Hmm - I haven't seen that one. Doesn't seem related to `cloneElement()` though, more `React.Children`.  Maybe open a new issue?  It would be useful to know the structure of `this.props.chidlren` before iteration.
