### ISSUE TITLE
Enzyme compatibility

### ISSUE THREAD

**Issue by developit** [developit/preact-compat#82]
As described in developit/preact#168 - it would be nice to have support for Enzyme.

**Comment by moimikey** [comment]
this lib seems like an interesting collaboration https://www.npmjs.com/package/preact-compat-enzyme

**Comment by developit** [comment]
Yup, @windyGex is awesome, he's been pushing on Enzyme compat.  I need to merge his PR!

**Comment by bkazi** [comment]
Any update on this?
since airbnb/enzyme#1007 has been merged, is there work on a Preact adapter for enzyme?
I'd like to help if I can

**Comment by ljharb** [comment]
More breaking changes are coming prior to enzyme v3; you'll want to wait until that's released before releasing any enzyme adapters.

**Comment by marvinhagemeister** [comment]
We now have an officially supported enzyme adapter. Check out https://github.com/preactjs/enzyme-adapter-preact-pure :+1:
